<a href="https://colab.research.google.com/github/iam-shankar/DSML-FB07-ML/blob/main/Python_Notes_FNB07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Live Notes

- Variables
- Data types
- Operators
- Data structures - Strings, Tuple, List, Dictionary, Set
- conditional statments - if, else
- Loops - for, while loop
- Functions
- File handling
- Error Handling
- OOPS

#Session 1 - Intro to Python

In [ ]:
print("Welcome to Python Module")

Welcome to Python Module

In [ ]:
print("Hello I am Shankar")

In [ ]:
#Python notes

## Variables

In [ ]:
print("Hello") #"Hello" --> String --> Text

Hello

In [ ]:
print(Hello) #Hello will be considered as a variable

NameError: name 'Hello' is not defined

NameError - It will search for the particular reference object or variable here Hello.

In [ ]:
Hello = "Hello I am Python"

In [ ]:
print(Hello)

Hello I am Python

In [ ]:
age=20
print(age)

20

In [ ]:
print(20)

20

In [ ]:
print(firstname)

NameError: name 'firstname' is not defined

In [ ]:
print(first name)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-13-f3e5aedc5263>, line 1)

In [ ]:
print(first,name)

NameError: name 'first' is not defined

#Rules for defining a variable

- Should not have space in between
- should not start with a number or special character
- Python is case-sensitive so as the variable name!
first_name
First_name
first_Name
First_Name

In [ ]:
first_name="Entri"
last_name="App"

In [ ]:
print(first_name,last_name)

Entri App

In [ ]:
print(First_name)

NameError: name 'First_name' is not defined

In [ ]:
print("First_name")

First_name

#Check type of the data

In [ ]:
type(first_name) #str -> String --> text

str

In [ ]:
age=20
type(age) #int --> integer

int

In [ ]:
height=5.10
type(height)

float

In [ ]:
willbuy = True
type(willbuy)

bool

#Dynamic Binding

In [ ]:
name="Entri"
type(name)

str

In [ ]:
name=20
type(name)

int

In [ ]:
name

20

#Getting input from the user

In [ ]:
name=input("Enter your name:")

Enter your name:Vijay

In [ ]:
name

'Vijay'

In [ ]:
age=input("Enter your age:")

Enter your age:20

In [ ]:
age

'20'

In [ ]:
number1=20
number2=25
result = number1 + number2

In [ ]:
print(result)

45

#Type error

In [ ]:
number1="20"
number2="25"
result = number1 + number2

In [ ]:
print(result)

2025

In [ ]:
number1="20"
number2=25
result = number1 + number2 #can only concatenate str (not "int") to str
print(result)

TypeError: can only concatenate str (not "int") to str

In [ ]:
number1=20
number2="25"
result = number1 + number2 # unsupported operand type(s) for +: 'int' and 'str'
print(result)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
number1=input("Enter the number1:")
number2=input("Enter the number2:")
result = number1 + number2
print(result)

Enter the number1:20
Enter the number2:25
2025

In [ ]:
number1

'20'

#Type casting

In [ ]:
number1="20"
type(number1)

str

In [ ]:
number1=int(number1)
type(number1)

int

In [ ]:
number1=int(input("Enter the number1:"))
number2=int(input("Enter the number2:"))
result = number1 + number2
print(result)

Enter the number1:20
Enter the number2:25
45

In [ ]:
number1="Entri"
int(number1)

ValueError: invalid literal for int() with base 10: 'Entri'

In [ ]:
number1="50"
int(number1)

50

#Session 2 - Strings and Tuple

In [ ]:
name # Variables stores the data temp. so if we try to access it later session is reconnected then python will not have the memory of any variable used!

NameError: name 'name' is not defined

In [ ]:
name="Entri"
type(name)

str

In [ ]:
username=input("Enter your name:")

Enter your name:Python

In [ ]:
type(username)

str

In [ ]:
userage=20

In [ ]:
username

'Python'

In [ ]:
print(username)

Python

In [ ]:
userage
username

'Python'

In [ ]:
print(userage)
print(username)

20
Python

#String Indexing and Slicing

-6 -5 -4 -3 -2 -1

P  y  t  h  o  n

0  1  2  3  4  5

![image.png]()

In [ ]:
username

'Python'

In [ ]:
username[3]

'h'

In [ ]:
username[0]

'P'

In [ ]:
username[-1]

'n'

#String SLicing

Syntax:

**Indexing**

variablename[index]

**Slicing**

***variablename[start_index:stop_index:step_index]***

- start_index - from where we need to start the slicing - default - 0

- stop_index - till which index we need to access note this is exclusive meaning the stop_index number that you are giving will not be considered it will consider till before number!

    Ex: 0:2 it will only consider index 0,1

    default --> end of the string/list

- step_index - default - 1 , we can change it if we want to make the slicing by jumping or skipping some numbers!

  0:5 - 0,1,2,3,4

  0:5:2 - 0,2,4

In [ ]:
text="Python"

In [ ]:
#variablename[start_index:stop_index:step_index]
text[0:3:1]

'Pyt'

In [ ]:
text[0:3]

'Pyt'

In [ ]:
text[:3]

'Pyt'

![image.png]()

In [ ]:
#variablename[start_index:stop_index:step_index]
text[-6:-3]

'Pyt'

In [ ]:
text[-3:]

'hon'

In [ ]:
text[2:-1]

'tho'

In [ ]:
text

'Python'

In [ ]:
text[0:]

'Python'

In [ ]:
text[::]

'Python'

In [ ]:
text[:]

'Python'

In [ ]:
text[::-1]

'nohtyP'

In [ ]:
url="https://www.google.com/" #url="https://www.entri.com/", url="https://www.google.com/"
domain=url[12:-5]
domain

'google'

#String methods ( check in in-app videos and PDF )

In [ ]:
text="python"

text.capitalize()

'Python'

In [ ]:
text.upper()

'PYTHON'

#String formatting

In [ ]:
username="Shankar"
usercity="Chennai"
print(username,usercity)

Shankar Chennai

In [ ]:
print("username=",username)

username= Shankar

In [ ]:
print("usercity=",usercity)

usercity= Chennai

In [ ]:
print("username=",username,"usercity=",usercity)

username= Shankar usercity= Chennai

In [ ]:
print("username=",username)
print("usercity=",usercity)

username= Shankar
usercity= Chennai

#f-string

In [ ]:
print(f'username={username} \nusercity={usercity}')

username=Shankar
usercity=Chennai

#Tuple

In [ ]:
username = "Entri","App"
username

('Entri', 'App')

In [ ]:
type(username)

tuple

In [ ]:
username = ("Entri","App")
type(username)

tuple

In [ ]:
mytuple= "Entri","App",12,4.0, True
mytuple

('Entri', 'App', 12, 4.0, True)

In [ ]:
username

('Entri', 'App')

#Tuple unpacking

In [ ]:
first_name,last_name = username
first_name

'Entri'

In [ ]:
last_name

'App'

In [ ]:
mytuple

('Entri', 'App', 12, 4.0, True)

In [ ]:
a,b,c,d,e=mytuple

In [ ]:
e

True

In [ ]:
first_name,last_name,newname = username

ValueError: not enough values to unpack (expected 3, got 2)

In [ ]:
len(username)

2

In [ ]:
first_name = username

In [ ]:
first_name

('Entri', 'App')

In [ ]:
len(mytuple)

5

In [ ]:
a,b,c,d=mytuple

ValueError: too many values to unpack (expected 4)

In [ ]:
mytuple[0]

'Entri'

In [ ]:
mytuple[-1]

True

In [ ]:
mytuple

('Entri', 'App', 12, 4.0, True)

In [ ]:
mytuple[:2]

('Entri', 'App')

In [ ]:
mytuple[-2:]

(4.0, True)

In [ ]:
mytuple[0]

'Entri'

In [ ]:
mytuple[0] = "Entri Coding"

TypeError: 'tuple' object does not support item assignment

In [ ]:
text[0] = 'M'

TypeError: 'str' object does not support item assignment

In [ ]:
numtuple = 10,15,3,24,2,3,4,5,6
len(numtuple)

9

In [ ]:
min(numtuple)

2

In [ ]:
max(numtuple)

6

In [ ]:
numtuple

(10, 15, 3, 24, 2, 3, 4, 5, 6)

In [ ]:
sorted(numtuple)

[2, 3, 3, 4, 5, 6, 10, 15, 24]

# task:
create tuple called mydetails and store your details such as name, age, city

and unpack it using variables name, age, city

In [ ]:
mydetails = ("Shankar","20","Ooty")
name, age, city = mydetails

In [ ]:
name

'Shankar'

#Session 3 - List

In [ ]:
mytuple = 1,2,3,"Entri"
mytuple

(1, 2, 3, 'Entri')

In [ ]:
mytuple[-1]

'Entri'

In [ ]:
mytuple[-1] = "Entri App"

TypeError: 'tuple' object does not support item assignment

In [ ]:
mytuple = 1,2,3,"Entri App"
mytuple

(1, 2, 3, 'Entri App')

In [ ]:
mylist=[1,2,3,"Entri","Elevate"]
mylist

[1, 2, 3, 'Entri', 'Elevate']

In [ ]:
mylist[0]

1

In [ ]:
mylist[-1] = "Coding" #mutable

In [ ]:
mylist

[1, 2, 3, 'Entri', 'Coding']

In [ ]:
type(mylist)

list

In [ ]:
mytuple= (1)
type(mytuple)

int

In [ ]:
mytuple= (1,) #singleton tuple
type(mytuple)

tuple

In [ ]:
mylist=[]
type(mylist)

list

#List Slicing

start_index:stop_index:step_index

**Slicing**

***variablename[start_index:stop_index:step_index]***

- start_index - from where we need to start the slicing - default - 0

- stop_index - till which index we need to access note this is exclusive meaning the stop_index number that you are giving will not be considered it will consider till before number!

    Ex: 0:2 it will only consider index 0,1

    default --> end of the string/list

- step_index - default - 1 , we can change it if we want to make the slicing by jumping or skipping some numbers!

  0:5 - 0,1,2,3,4

  0:5:2 - 0,2,4

#task

Create a list called mydetails with your personal details such as name, age, city, email, Profession

Then try to display the first 3 data from the list

last 3 data from the list

any 2 data in between the list

use both positive and negative indexing

last element from the list

Reverse the elements in the list

Python List Practice Questions - https://www.geeksforgeeks.org/python-list-exercise/

In [ ]:
mylist=[1,2,3,"Entri","Elevate"]

In [ ]:
mydetails =["thiru",23,"ooty","thiru@gmail.com","Aspiring Data Analyst"]

In [ ]:
mydetails[0:3]

['thiru', 23, 'ooty']

In [ ]:
mydetails[-3:]

['ooty', 'thiru@gmail.com', 'Aspiring Data Analyst']

In [ ]:
mydetails[2:4]

['ooty', 'thiru@gmail.com']

In [ ]:
mydetails[4]

'Aspiring Data Analyst'

In [ ]:
mydetails[-1]

'Aspiring Data Analyst'

In [ ]:
mydetails[::-1]

['Aspiring Data Analyst', 'thiru@gmail.com', 'ooty', 23, 'thiru']

#Adding new elements to the list

- Append - can be used to add the element at the end of the list
- insert - to add the element in a specified index position
- extend - to add iterables

In [ ]:
mydetails

['thiru', 23, 'ooty', 'thiru@gmail.com', 'Aspiring Data Analyst']

In [ ]:
mydetails.append("Engineering")
mydetails

['thiru',
 23,
 'ooty',
 'thiru@gmail.com',
 'Aspiring Data Analyst',
 'Engineering']

In [ ]:
mydetails.insert(3,"TN")
mydetails

['thiru',
 23,
 'ooty',
 'TN',
 'thiru@gmail.com',
 'Aspiring Data Analyst',
 'Engineering']

In [ ]:
myskills=["Excel","PowerBI","MySQL","Python"]
mydetails.insert(-2,myskills)
mydetails

['thiru',
 23,
 'ooty',
 'TN',
 'thiru@gmail.com',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering']

In [ ]:
mydetails[-3]

['Excel', 'PowerBI', 'MySQL', 'Python']

In [ ]:
myproject=["Healthcare analysis","Loan data analysis"]
mydetails.extend(myproject)
mydetails

['thiru',
 23,
 'ooty',
 'TN',
 'thiru@gmail.com',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'Loan data analysis']

In [ ]:
mydetails[3]=myskills
mydetails

['thiru',
 23,
 'ooty',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'thiru@gmail.com',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'Loan data analysis']

In [ ]:
mydetails[3:3]=myskills
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'thiru@gmail.com',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'Loan data analysis']

In [ ]:
myexperience=("DA","DA Intern")
mydetails.extend(myexperience)
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'thiru@gmail.com',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'Loan data analysis',
 'DA',
 'DA Intern']

#task
mydetails

--> add new element may be certification detail at the end

--> add any 2 skill after your mail

In [ ]:
mailindex = mydetails.index('thiru@gmail.com')
mydetails[mailindex+1:mailindex+1] = ["Python","MySQL"]
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Python',
 'MySQL',
 'thiru@gmail.com',
 'Python',
 'MySQL',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'Loan data analysis',
 'DA',
 'DA Intern']

#Removing elements

pop() - removes the last element if no index is given, if index given removes that value and returns the value

remove() - to remove the specific element

del - it can be used to remove a single element, range of elements also list

clear()

In [ ]:
mydetails.pop()

'DA Intern'

In [ ]:
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Python',
 'MySQL',
 'thiru@gmail.com',
 'Python',
 'MySQL',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'Loan data analysis',
 'DA']

In [ ]:
mydetails.pop(-2)

'Loan data analysis'

In [ ]:
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Python',
 'MySQL',
 'thiru@gmail.com',
 'Python',
 'MySQL',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'DA']

In [ ]:
mydetails.remove("Python")

In [ ]:
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Python',
 'MySQL',
 'thiru@gmail.com',
 'Python',
 'MySQL',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'DA']

In [ ]:
mydetails.remove(['Excel', 'PowerBI', 'MySQL', 'Python'])
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 'MySQL',
 'thiru@gmail.com',
 'Python',
 'MySQL',
 ['Excel', 'PowerBI', 'MySQL', 'Python'],
 'Aspiring Data Analyst',
 'Engineering',
 'Healthcare analysis',
 'DA']

In [ ]:
del mydetails[-5:]

In [ ]:
mydetails

['thiru',
 23,
 'ooty',
 'Excel',
 'PowerBI',
 'MySQL',
 'Python',
 'MySQL',
 'thiru@gmail.com',
 'Python',
 'MySQL']

#List copy
Shallow Copy vs Deep Copy

In [ ]:
l1=[1,2,3,4]
l2=l1

In [ ]:
l1

[1, 2, 3, 4]

In [ ]:
l2

[1, 2, 3, 4]

In [ ]:
l2[-1]=100

In [ ]:
l2

[1, 2, 3, 100]

In [ ]:
l1

[1, 2, 3, 100]

In [ ]:
l1

[1, 2, 3, 100]

![image.png]()

In [ ]:
l2=l1.copy() #shallow copy
l2

[1, 2, 3, 100]

In [ ]:
l2[-1]="NEw Data"
l2

[1, 2, 3, 'NEw Data']

In [ ]:
l1

[1, 2, 3, 100]

# nested list

In [ ]:
l1 = [1,2,3,["Entri","DSML"]]
l1

[1, 2, 3, ['Entri', 'DSML']]

In [ ]:
l2=l1.copy()
l2

[1, 2, 3, ['Entri', 'DSML']]

In [ ]:
l2[-1]

['Entri', 'DSML']

In [ ]:
l2[-1][-1]

'DSML'

In [ ]:
l2[-1][-1] = "DA"
l2

[1, 2, 3, ['Entri', 'DA']]

In [ ]:
l1

[1, 2, 3, ['Entri', 'DA']]

#Deep copy

![image.png]()

In [ ]:
import copy
l2=copy.deepcopy(l1)
l2

[1, 2, 3, ['Entri', 'DA']]

In [ ]:
l2[-1][-1] = "AI Dev"
l2

[1, 2, 3, ['Entri', 'AI Dev']]

In [ ]:
l1

[1, 2, 3, ['Entri', 'DA']]

#Session 4 - Dictionary and Sets

In [ ]:
mydict={}
type(mydict)

dict

In [ ]:
mydict={"K1":"V1", "K2":"V2", "K3":"V3" }
mydict

{'K1': 'V1', 'K2': 'V2', 'K3': 'V3'}

In [ ]:
mydict={"K1":"V1", "K2":"V2", "K3":"V3","k4":3,"k5":[1,2,3] }
mydict

{'K1': 'V1', 'K2': 'V2', 'K3': 'V3', 'k4': 3, 'k5': [1, 2, 3]}

In [ ]:
mydict['K2']

'V2'

In [ ]:
mydict['k2']

KeyError: 'k2'

In [ ]:
mydict={"K1":"V1", "K2":"V2", "K3":"V3","k4":30,"k5":[1,2,3],"K6":{"innerkey":"innerval","innerke2":"val2"} }
mydict

{'K1': 'V1',
 'K2': 'V2',
 'K3': 'V3',
 'k4': 30,
 'k5': [1, 2, 3],
 'K6': {'innerkey': 'innerval', 'innerke2': 'val2'}}

In [ ]:
mydict['k5']

[1, 2, 3]

In [ ]:
mydict['k5'][-1]

3

In [ ]:
mydict['K6']

{'innerkey': 'innerval', 'innerke2': 'val2'}

In [ ]:
mydict['K6']['innerke2']

'val2'

In [ ]:
mydict={"K1":"V1", "K2":"V2", "K3":"V3","k4":30,"k5":[1,2,3],"K6":{"innerkey":"innerval","innerke2":"val2"},1:5,2:"Text" }
mydict

{'K1': 'V1',
 'K2': 'V2',
 'K3': 'V3',
 'k4': 30,
 'k5': [1, 2, 3],
 'K6': {'innerkey': 'innerval', 'innerke2': 'val2'},
 1: 5,
 2: 'Text'}

In [ ]:
mydict[2]

'Text'

In [ ]:
mydict[3]

KeyError: 3

In [ ]:
mydict.get(2)

'Text'

In [ ]:
mydict.get(3)

In [ ]:
mydict.get(3,"Key not found!")

'Key not found!'

In [ ]:
mydict.get('K1',"Key not found!")

'V1'

In [ ]:
mydict.get(2,"Key not found!")

'Text'

In [ ]:
mydict.get(5,"Key not found!")

'Key not found!'

In [ ]:
mydict.setdefault(2,"Key not found!")

'Text'

In [ ]:
mydict.setdefault(3,"New value!")

'New value!'

In [ ]:
mydict

{'K1': 'V1',
 'K2': 'V2',
 'K3': 'V3',
 'k4': 30,
 'k5': [1, 2, 3],
 'K6': {'innerkey': 'innerval', 'innerke2': 'val2'},
 1: 5,
 2: 'Text',
 3: 'New value!'}

#Task

1. create a dictionary called student_dict with details such as name, age
2. Print the dictionary
3. change name
4. Retrieve the age details
5. Try to retrieve city details ( make sure your code should not produce any errors )

In [ ]:
student_dict = { "Name" : "selva mani",  "Age" : 20 }
print(student_dict)

{'Name': 'selva mani', 'Age': 20}

In [ ]:
student_dict ["name"]="mani" #creating new key value
print(student_dict)

{'Name': 'selva mani', 'Age': 20, 'name': 'mani'}

In [ ]:
student_dict ["Name"]="mani"
print(student_dict)

{'Name': 'mani', 'Age': 20, 'name': 'mani'}

In [ ]:
student_dict ["Age"]

20

In [ ]:
student_dict.get("city", "No City details")

'No City details'

#adding new key value pairs

In [ ]:
student_dict ["City"]="Chennai"
student_dict

{'Name': 'mani',
 'Age': 20,
 'name': 'mani',
 'new key': 'new value',
 'City': 'Chennai'}

In [ ]:
project_details={"Excel":"Healthcare Analysis","PowerBI":"Bank Loan analysis"}

In [ ]:
student_dict.update(project_details)
student_dict

{'Name': 'mani',
 'Age': 20,
 'name': 'mani',
 'new key': 'new value',
 'City': 'Chennai',
 'Excel': 'Healthcare Analysis',
 'PowerBI': 'Bank Loan analysis'}

In [ ]:
student_dict.keys()

dict_keys(['Name', 'Age', 'name', 'new key', 'City', 'Excel', 'PowerBI'])

In [ ]:
student_dict.values()

dict_values(['mani', 20, 'mani', 'new value', 'Chennai', 'Healthcare Analysis', 'Bank Loan analysis'])

In [ ]:
student_dict.items()

dict_items([('Name', 'mani'), ('Age', 20), ('name', 'mani'), ('new key', 'new value'), ('City', 'Chennai'), ('Excel', 'Healthcare Analysis'), ('PowerBI', 'Bank Loan analysis')])

In [ ]:
sampledetails=student_dict.items()
sampledetails

dict_items([('Name', 'mani'), ('Age', 20), ('name', 'mani'), ('new key', 'new value'), ('City', 'Chennai'), ('Excel', 'Healthcare Analysis'), ('PowerBI', 'Bank Loan analysis')])

In [ ]:
type(sampledetails)

dict_items

In [ ]:
sampledetails[1]

TypeError: 'dict_items' object is not subscriptable

#Removing elements


pop

In [ ]:
mydict.pop('address')

KeyError: 'address'

In [ ]:
mydict.pop('address',"Key Not Found")

'Key Not Found'

In [ ]:
student_dict['name']

'mani'

In [ ]:
student_dict.pop('name',"Key Not Found")

'mani'

In [ ]:
student_dict

{'Name': 'mani',
 'Age': 20,
 'new key': 'new value',
 'City': 'Chennai',
 'Excel': 'Healthcare Analysis',
 'PowerBI': 'Bank Loan analysis'}

In [ ]:
del student_dict['new key']

In [ ]:
student_dict

{'Name': 'mani',
 'Age': 20,
 'City': 'Chennai',
 'Excel': 'Healthcare Analysis',
 'PowerBI': 'Bank Loan analysis'}

In [ ]:
student_dict.clear()

In [ ]:
student_dict

{}

In [ ]:
student_dict['K1']="Value1"

In [ ]:
student_dict

{'K1': 'Value1'}

In [ ]:
del student_dict

In [ ]:
student_dict

NameError: name 'student_dict' is not defined

## Copy vs Deep Copy

In [ ]:
d1={'k1':1,"k2":2,"k3":[1,2,3]}
d2=d1
d2

{'k1': 1, 'k2': 2, 'k3': [1, 2, 3]}

In [ ]:
d2['k2']=100
d2

{'k1': 1, 'k2': 100, 'k3': [1, 2, 3]}

In [ ]:
d1

{'k1': 1, 'k2': 100, 'k3': [1, 2, 3]}

In [ ]:
d2=d1.copy()
d2

{'k1': 1, 'k2': 100, 'k3': [1, 2, 3]}

In [ ]:
d2['k2']=500

In [ ]:
d2

{'k1': 1, 'k2': 500, 'k3': [1, 2, 3]}

In [ ]:
d1

{'k1': 1, 'k2': 100, 'k3': [1, 2, 3]}

In [ ]:
d2['k3'][-1] = 300

In [ ]:
d2

{'k1': 1, 'k2': 500, 'k3': [1, 2, 300]}

In [ ]:
d1

{'k1': 1, 'k2': 100, 'k3': [1, 2, 300]}

In [ ]:
import copy

d2=copy.deepcopy(d1)
d2

{'k1': 1, 'k2': 100, 'k3': [1, 2, 300]}

In [ ]:
d2['k3'][-1] = "Text"
d2

{'k1': 1, 'k2': 100, 'k3': [1, 2, 'Text']}

In [ ]:
d1

{'k1': 1, 'k2': 100, 'k3': [1, 2, 300]}

#Sets

In [ ]:
myset={1,2,3}
type(myset)

set

In [ ]:
myset

{1, 2, 3}

In [ ]:
myset={1,2,3,4,1,2,3}
myset

{1, 2, 3, 4}

In [ ]:
myset=set()

In [ ]:
myset

set()

In [ ]:
myset.add("Cricket")
myset

{'Cricket'}

In [ ]:
myset.add("Tennis")
myset

{'Cricket', 'Tennis'}

In [ ]:
l1=["Volley ball","Basket ball","Soccer"]
myset.add(l1)

TypeError: unhashable type: 'list'

In [ ]:
myset.add(tuple(l1))

In [ ]:
myset

{('Volley ball', 'Basket ball', 'Soccer'), 'Cricket', 'Tennis'}

In [ ]:
myset.update(l1)
myset

{('Volley ball', 'Basket ball', 'Soccer'),
 'Basket ball',
 'Cricket',
 'Soccer',
 'Tennis',
 'Volley ball'}

In [ ]:
myset.remove(('Volley ball', 'Basket ball', 'Soccer'))
myset

{'Basket ball', 'Cricket', 'Soccer', 'Tennis', 'Volley ball'}

In [ ]:
myset.remove("Foot ball")
myset

KeyError: 'Foot ball'

In [ ]:
myset.discard('Soccer')

In [ ]:
myset

{'Basket ball', 'Cricket', 'Tennis', 'Volley ball'}

In [ ]:
myset.remove('Soccer')

KeyError: 'Soccer'

In [ ]:
myset.discard('Soccer')

#Set Operations

Union - |

Intersection - &

difference - '-'

Symmetry difference - ^

In [ ]:
ipl2024CSK = {'MSD','Rahane','Ruthraj','Moeen Ali','Shivam Dube','Deepak Chahar','Matheesha Pathirana','Ravindra Jadeja'}
ipl2025CSK = {'MSD','Ruthraj','Shivam Dube','Matheesha Pathirana','Ravindra Jadeja','Shaik Rasheed','Ashwin','Rahul Tripathi'}

In [ ]:
ipl2024CSK

{'Deepak Chahar',
 'MSD',
 'Matheesha Pathirana',
 'Moeen Ali',
 'Rahane',
 'Ravindra Jadeja',
 'Ruthraj',
 'Shivam Dube'}

In [ ]:
#Unique Players
unique_players= ipl2024CSK | ipl2025CSK
unique_players

{'Ashwin',
 'Deepak Chahar',
 'MSD',
 'Matheesha Pathirana',
 'Moeen Ali',
 'Rahane',
 'Rahul Tripathi',
 'Ravindra Jadeja',
 'Ravindra JadejaShaik Rasheed',
 'Ruthraj',
 'Shivam Dube'}

In [ ]:
#Common Players
common_players = ipl2024CSK & ipl2025CSK
common_players

{'MSD', 'Matheesha Pathirana', 'Ravindra Jadeja', 'Ruthraj', 'Shivam Dube'}

In [ ]:
Playersnotx1 = ipl2024CSK - ipl2025CSK
Playersnotx1

{'Deepak Chahar', 'Moeen Ali', 'Rahane'}

In [ ]:
newplayers = ipl2025CSK - ipl2024CSK
newplayers

{'Ashwin', 'Rahul Tripathi', 'Shaik Rasheed'}

In [ ]:
diff3 = ipl2025CSK ^ ipl2024CSK
diff3

{'Ashwin',
 'Deepak Chahar',
 'Moeen Ali',
 'Rahane',
 'Rahul Tripathi',
 'Shaik Rasheed'}

In [ ]:
diff3 = ipl2024CSK ^ ipl2025CSK
diff3

{'Ashwin',
 'Deepak Chahar',
 'Moeen Ali',
 'Rahane',
 'Rahul Tripathi',
 'Shaik Rasheed'}

In [ ]:
ipl2025CSK.add('Dewald Brevis')
ipl2025CSK

{'Ashwin',
 'Dewald Brevis',
 'MSD',
 'Matheesha Pathirana',
 'Rahul Tripathi',
 'Ravindra Jadeja',
 'Ruthraj',
 'Shaik Rasheed',
 'Shivam Dube'}

In [ ]:
type(ipl2025CSK)

set

In [ ]:
ipl2025CSK=frozenset(ipl2025CSK)
type(ipl2025CSK)

frozenset

In [ ]:
ipl2025CSK.add('Ghosh')
ipl2025CSK

AttributeError: 'frozenset' object has no attribute 'add'

In [ ]:
diff3 = ipl2024CSK ^ ipl2025CSK
diff3

{'Ashwin',
 'Deepak Chahar',
 'Dewald Brevis',
 'Moeen Ali',
 'Rahane',
 'Rahul Tripathi',
 'Shaik Rasheed'}

#Session 5 - Operators and COntrol Statements

#Operators

- Arithmetics
- Relational
- Logical
- Assignment
- Bitwise

In [ ]:
a=9
b=2
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)

11
7
18
4.5
1
4

In [ ]:
print(a**b)

81

In [ ]:
a>b

True

In [ ]:
b>a

False

In [ ]:
a==b

False

In [ ]:
a!=b

True

In [ ]:
a>=b

True

In [ ]:
b>=a

False

In [ ]:
b<=a

True

In [ ]:
c=10

In [ ]:
a>b and a>c

False

In [ ]:
a>b

True

In [ ]:
a>c

False

In [ ]:
True and False

False

In [ ]:
True and True

True

In [ ]:
True or False

True

In [ ]:
True or True

True

In [ ]:
#0+1=1 --> or

#0*1=0 --> and

a=1
a=a+1

In [ ]:
a

2

In [ ]:
a+=1 #a=a+1
a

3

#Control Statement if, else, elif

In [ ]:
if(True):
  pass
print("IF logic will get executed")

IF logic will get executed

In [ ]:
if(True):
  print("IF logic will get executed")
else:
  print("Else logic will get executed")

IF logic will get executed

In [ ]:
if(False):
  print("IF logic will get executed")
else:
  print("Else logic will get executed")

Else logic will get executed

In [ ]:
if(False):
  print("IF logic will get executed")
elif(True):
  print("ElIF logic will get executed")
else:
  print("Else logic will get executed")

ElIF logic will get executed

In [ ]:
if(False):
  print("IF logic will get executed")
elif(True):
  print("ElIF 1 logic will get executed")
elif(True):
  print("ElIF 2 logic will get executed")
else:
  print("Else logic will get executed")

ElIF 1 logic will get executed

In [ ]:
if(True):
  print("IF logic will get executed")
elif(True):
  print("ElIF 1 logic will get executed")
elif(True):
  print("ElIF 2 logic will get executed")
else:
  print("Else logic will get executed")

IF logic will get executed

In [ ]:
if(False):
  print("IF logic will get executed")
elif(False):
  print("ElIF 1 logic will get executed")
elif(False):
  print("ElIF 2 logic will get executed")
else:
  print("Else logic will get executed")

Else logic will get executed

In [ ]:
if(False):
  print("IF logic will get executed")
elif(False):
  print("ElIF 1 logic will get executed")
elif(False):
  print("ElIF 2 logic will get executed")

In [ ]:
#n/2 --> rem --> 0 - Even if not odd num
n=4
n%2==0

True

In [ ]:
if(n%2==0):
  print("Even Number")
else:
  print("Odd number")

Even Number

In [ ]:
n=int(input("Enter a number:"))

Enter a number:22

In [ ]:
if(n%2==0):
  print("Even Number")
elif(n%2!=0):
  print("Odd number")
else:
  print("Something went wrong pls try again!")

Even Number

#Task:

Create a program to calculate which number is greater
1. create variables called number1 and number2 and get input from the user
2. Check which number is greater

3. Suppose if both the numbers are given same input what will be the output how you will handle it further

In [ ]:
number1 = float(input("Enter the first number: "))
number2 = float(input("Enter the second number: "))
if number1 > number2:
    print(f"{number1} is greater than {number2}")
elif number2 > number1:
    print(f"{number2} is greater than {number1}")
else:
    print(f"Both numbers are equal: {number1}")

Enter the first number: 8
Enter the second number: 5
8.0 is greater than 5.0

In [ ]:
number1=10
number2 =10
if number1 > number2:
    print(f"{number1} is greater than {number2}")
else:
    print(f"{number2} is greater than {number1}")

#Task

1. Create 3 variables and check which is greatest of all!

Hint: you can use and operator

In [ ]:
number1 = int(input("Enter the first number: "))
number2 = int(input("Enter the second number: "))
number3 = int(input("Enter the third number: "))
if number1>number2 and number1 >number3:
  print("first is greater")
elif number2>number1 and number2 >number3:
  print("second is greater")
elif number3>number1 and number3 >number2:
  print("three is greater")
else:
  print("two or more numbers areequal and greates")

Enter the first number: 10
Enter the second number: 10
Enter the third number: 10
two or more numbers areequal and greates

#Task

Create a program get the age of the user and Country of the user
check if the age is above 18 or if he is from India then print the person is eligible else tell that the person is not eligible...

In [ ]:
age = int(input("Enter your age: "))
country = input("Enter your country: ")


if age > 18 or country == "india":
    print("The person is eligible.")
else:
    print("The person is not eligible.")

Enter your age: 17
Enter your country: US
The person is not eligible.

#Ternary Operator

value if true if condition else value if false

In [ ]:
if(n%2==0):
  print("Even Number")
else:
  print("Odd number")

Even Number

In [ ]:
"Even Number" if(50%2==0) else "Odd number"

'Even Number'

In [ ]:
fb07learners = ['Malathi','Shankar',"Manigandan","Mahalakshmi"]

username=input("Enter your name:")

if username in fb07learners:
  print("Your session starts on Friday 11am")
else:
  print("You are not part of this batch!")

Enter your name:Alagu Manigandan
You are not part of this batch!

In [ ]:
username in fb07learners

False

In [ ]:
"Your session starts on Friday 11am" if username in fb07learners else "You are not part of this batch!"

'You are not part of this batch!'

#Task: Student Grade Checker

- Get student name
- Get 5 subject marks out of 100 from the user
- calculate the total mark
- calculate the average
- Based on average score classify the grade

Grade system:
above 90 -> A

above 70 to 90 - B

above 50 to 70 - C

below 50 - D


Finally print the score card

Name:

Sub1:

Sub2:

Sub3:

Sub4:

sub5:

Total:

Grade:

In [ ]:
studentname=(input("Enter the Student Name:"))
Sub1= int(input("Enter the Subject 1 Mark :"))
Sub2= int(input("Enter the Subject 2 Mark :"))
Sub3= int(input("Enter the Subject 3 Mark:"))
Sub4= int(input("Enter the Subject 4 Mark:"))
Sub5= int(input("Enter the Subject Mark5:"))
total_mark = Sub1+Sub2+Sub3+Sub4+Sub5
average = total_mark/100
if(total_mark>90):
  grade = "A"
elif(total_mark<90 and total_mark>70):
  grade = "B"
elif(total_mark<70 and total_mark>50):
  grade = "C"
elif(total_mark<50 ):
  grade = "D"
print (f'Name:{studentname}\nSub1:{Sub1}\n{Sub2},{Sub3},{Sub4},{Sub5},{total_mark},{grade}')

Enter the Student Name:dd
Enter the Subject 1 Mark :77
Enter the Subject 2 Mark :88
Enter the Subject 3 Mark:88
Enter the Subject 4 Mark:77
Enter the Subject Mark5:66
Name:dd
77,88,88,77,66,396,A

# Session 6 - While Loop

while condition:

  loop logic

In [ ]:
print(1)
print(2)
print(3)
print(4)
print(5)

1
1
1
1
1

In [ ]:
'''while True:
  print(1)'''
#this code will run infinite time
  #loop logic

In [ ]:
count=1
while count<=10:
  print(count)#1, #2
  count=count+1 #count=2+1 = 3

1
2
3
4
5
6
7
8
9
10

In [ ]:
count=1
while count<=10:
  print(f'Iteration:{count}')
  print(count)#1, #2
  count=count+1
  print(f'After increment:{count}')

Iteration:1
1
After increment:2
Iteration:2
2
After increment:3
Iteration:3
3
After increment:4
Iteration:4
4
After increment:5
Iteration:5
5
After increment:6
Iteration:6
6
After increment:7
Iteration:7
7
After increment:8
Iteration:8
8
After increment:9
Iteration:9
9
After increment:10
Iteration:10
10
After increment:11

In [ ]:
count=1
while count<=5:
  print(count)
  count=count+1

print("Loop has ended")

1
2
3
4
5
Loop has ended

In [ ]:
count=1
while count<=5:
  print(count)
  count=count+1
else:
  print("In else part")

print("Loop has ended")

1
2
3
4
5
In else part
Loop has ended

#break and continue

break - stop the loop when desired result achieved

continue - continue or skip the current itration

In [ ]:
count=1
while count<=10:
  print(count)
  if count==5:
    print("Desired result achieved")
    break
  count=count+1
else:
  print("In else part")

print("Loop has ended")

1
2
3
4
5
Desired result achieved
Loop has ended

In [ ]:
count=0
while count<10:
  count=count+1
  if count%2==0: #skipping even numbers
    continue
  print(count)

else:
  print("In else part")

print("Loop has ended")

1
3
5
7
9
In else part
Loop has ended

#Task

1. Print Day 1 to Day 30

Day 1

Day 2

...

Day 30

In [ ]:
day=1
while day<=30:
  print(f"Day {day}")
  day+=1

Day 1
Day 2
Day 3
Day 4
Day 5
Day 6
Day 7
Day 8
Day 9
Day 10
Day 11
Day 12
Day 13
Day 14
Day 15
Day 16
Day 17
Day 18
Day 19
Day 20
Day 21
Day 22
Day 23
Day 24
Day 25
Day 26
Day 27
Day 28
Day 29
Day 30

#Login Scenario

Module 1:

1. Create a variabled called password and store a value ex: pwd="entri"

2. Get the username and pwd from user

3. check if the user entered password and our pwd is same, if so print welcome "Entri" else display passowrd incorrect please try again!

Module 2:

4. Try to get the password again if the user entered wrong password

Module 3:

5. Restrict only 3 attempts else display Out of attempts try again after sometime

Module 4:

6. In case if the user entered the correct pwd in the first attempt itself display the welcome username

7. In case if the user is entered mistakenly 2 letters or 3 leeter or 1 single letter we can alert them and ask the password again

Module 1:

Create a variabled called password and store a value ex: pwd="entri"

Get the username and pwd from user

check if the user entered password and our pwd is same, if so print welcome "Entri" else display passowrd incorrect please try again!

In [ ]:
pwd="entri"

username=input("Enter the username:")
userpwd=input("Enter the password:")

if userpwd == pwd:
  print(f"Welcome {username}!")
else:
  print("passowrd incorrect please try again!")

Enter the username:app
Enter the password:app
passowrd incorrect please try again!

Module 2:

Try to get the password again if the user entered wrong password

Module 3:

Restrict only 3 attempts else display Out of attempts try again after sometime

In [ ]:
pwd="entri"
username=input("Enter the username:")
attempts = 3
while attempts>0:
  userpwd=input("Enter the password:")
  attempts = attempts -1
  if userpwd == pwd:
    print(f"Welcome {username}!")
  else:
    print(f"passowrd incorrect please try again! Attempts Remaining - {attempts}")
else:
  print("Out of attempts try again after sometime")

Enter the username:Naren
Enter the password:3
passowrd incorrect please try again! Attempts Remaining - 2
Enter the password:4
passowrd incorrect please try again! Attempts Remaining - 1
Enter the password:5
passowrd incorrect please try again! Attempts Remaining - 0
Out of attempts try again after sometime

Module 4:

In case if the user entered the correct pwd in the first attempt itself display the welcome username

In [ ]:
pwd="entri"
username=input("Enter the username:")
attempts = 3
while attempts>0:
  userpwd=input("Enter the password:")
  attempts = attempts -1
  if userpwd == pwd:
    print(f"Welcome {username}!")
  else:
    print(f"passowrd incorrect please try again! Attempts Remaining - {attempts}")
else:
  print("Out of attempts try again after sometime")

Enter the username:Naren
Enter the password:entri
Welcome Naren!
Enter the password:ff
passowrd incorrect please try again! Attempts Remaining - 1
Enter the password:ff
passowrd incorrect please try again! Attempts Remaining - 0
Out of attempts try again after sometime

In [ ]:
pwd="entri"
username=input("Enter the username:")
attempts = 3
while attempts>0:
  userpwd=input("Enter the password:")
  attempts = attempts -1
  if userpwd == pwd:
    print(f"Welcome {username}!")
    break
  else:
    print(f"passowrd incorrect please try again! Attempts Remaining - {attempts}")
else:
  print("Out of attempts try again after sometime")

Enter the username:Naren
Enter the password:Entri
passowrd incorrect please try again! Attempts Remaining - 2
Enter the password:entri
Welcome Naren!


7. In case if the user is entered mistakenly 2 letters or 3 leeter or 1 single letter we can alert them and ask the password again

#Final Code

In [ ]:
pwd="entri"
username=input("Enter the username:")
attempts = 3
while attempts>0:
  userpwd=input("Enter the password:")
  if len(userpwd) <4:
    print("Enter atleast 4 characters!")
    continue
  attempts = attempts -1
  if userpwd == pwd:
    print(f"Welcome {username}!")
    break
  else:
    print(f"passowrd incorrect please try again! Attempts Remaining - {attempts}")
else:
  print("Out of attempts try again after sometime")

Enter the username:Naren
Enter the password:1
Enter atleast 4 characters!
Enter the password:2
Enter atleast 4 characters!
Enter the password:appp
passowrd incorrect please try again! Attempts Remaining - 2
Enter the password:entri
Welcome Naren!

#Task:

Get a number from the user and print the sum of all the numbers inside

ex: enter a number: 3

3+2+1= 6

6

enter a number: 5

5+4+3+2+1 = 15

Hint: While loop, use extra variable to store the sum valuye'

In [ ]:
count=1
sum=0
number=int(input("Enter a number:"))
while count<=number:
  print("count=",count)
  print("sum=",sum)
  sum = sum +count # 0 + 1
  count+=1
print("Final Sum:",sum)

Enter a number:5
count= 1
sum= 0
count= 2
sum= 1
count= 3
sum= 3
count= 4
sum= 6
count= 5
sum= 10
Final Sum: 15

In [ ]:
count=1
n=3
sum=0
while count<=n:
  print(count)
  sum = sum + count #0 + 1 sum=1, sum = 1 +2 sum =3, sum = 3+3 sum=6
  count=count+1
print("Sum=",sum)

1
2
3
Sum= 6

In [ ]:
count=1
n=3
sum=0
while count<=n:
  print("Iteration:",count)
  print("Count=",count)
  print("Sum=",sum)
  print(f"Calculate sum = sum + count which is sum={sum}+{count}")
  sum = sum + count #0 + 1 sum=1, sum = 1 +2 sum =3, sum = 3+3 sum=6
  print("calculated sum=",sum)
  count=count+1
print("Sum=",sum)

Iteration: 1
Count= 1
Sum= 0
Calculate sum = sum + count which is sum=0+1
calculated sum= 1
Iteration: 2
Count= 2
Sum= 1
Calculate sum = sum + count which is sum=1+2
calculated sum= 3
Iteration: 3
Count= 3
Sum= 3
Calculate sum = sum + count which is sum=3+3
calculated sum= 6
Sum= 6

#Session 7 - For Loop


for item in range/sequence:

  for logic

In [ ]:
count=1
while count<=5:
  print(count)
  count+=1

1
2
3
4
5

In [ ]:
range(10) #0,9

range(0, 10)

range(start, stop, step)

start - 0

stop - mention

step - 1


10,0,1

10,0,-1

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
for number in range(10):
  print(number)

0
1
2
3
4
5
6
7
8
9

In [ ]:
for number in range(1,11):
  print(f'Iteration:{number}')

Iteration:1
Iteration:2
Iteration:3
Iteration:4
Iteration:5
Iteration:6
Iteration:7
Iteration:8
Iteration:9
Iteration:10

In [ ]:
#using while loop print the even numbers between a range ex: 1 to 10
i = 1
while i <= 10:
  if i % 2 == 0:
    print("Even number:", i)
  i += 1

Even number: 2
Even number: 4
Even number: 6
Even number: 8
Even number: 10

In [ ]:
for number in range(1,11):
  if number % 2 == 0:
    print(f'Iteration:{number}')

Iteration:2
Iteration:4
Iteration:6
Iteration:8
Iteration:10

In [ ]:
for number in range(10,0,-1):
  if number % 2 == 0:
    print(f'Iteration:{number}')

Iteration:10
Iteration:8
Iteration:6
Iteration:4
Iteration:2

In [ ]:
for number in range(10,0,-1):
  print(f'Iteration:{number}')

Iteration:10
Iteration:9
Iteration:8
Iteration:7
Iteration:6
Iteration:5
Iteration:4
Iteration:3
Iteration:2
Iteration:1

In [ ]:
for i in range(5):
  print(i)
else:
  print("Loop has ended!")
print("Outside the loop")

0
1
2
3
4
Loop has ended!
Outside the loop

#break and continue

In [ ]:
for i in range(1,11):

  if i == 5:
    print("Desired result acheived!") #p1
    break
  print(i) #p2

else:
  print("Loop has ended!") #p3
print("Outside the loop") #p4

#p2
#p2
#p2
#p2
#p1
#p4

1
2
3
4
Desired result acheived!
Outside the loop

In [ ]:
for i in range(1,11):

  if i == 5:
    print("Skip this number!") #p1
    continue
  print(i) #p2

else:
  print("Loop has ended!") #p3
print("Outside the loop") #p4

1
2
3
4
Skip this number!
6
7
8
9
10
Loop has ended!
Outside the loop

#Task

- get the start number and stop number from the user and print the numbers
ex: start=1, stop=10, print 1 to 10

- within that range print the even numbers 2,4,6,8,10

- within that range find the sum of even numbers - 30

In [ ]:
start=int(input("Enter the start number:"))
stop=int(input("Enter the stop number:"))
total=0
for num in range(start, stop+1):
  if num % 2 == 0:
    print(num)
    total += num
print("Sum of even numbers  is:", total)

Enter the start number:5
Enter the stop number:50
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
Sum of even numbers  is: 644

In [ ]:
modules = ['Excel','PowerBI','SQL','Python']

for module in modules:
  print(module)

Excel
PowerBI
SQL
Python

In [ ]:
for module in "modules":
  print(module)

m
o
d
u
l
e
s

In [ ]:
for index,module in enumerate(modules,1):
  print(index,module)

1 Excel
2 PowerBI
3 SQL
4 Python

In [ ]:
statesAndCapitals = {
    'TamilNadu': 'Chennai',
    'Maharashtra': 'Mumbai',
    'Rajasthan': 'Jaipur',
    'Bihar': 'Patna'
}
statesAndCapitals

{'TamilNadu': 'Chennai',
 'Maharashtra': 'Mumbai',
 'Rajasthan': 'Jaipur',
 'Bihar': 'Patna'}

In [ ]:
statesAndCapitals.keys()

dict_keys(['TamilNadu', 'Maharashtra', 'Rajasthan', 'Bihar'])

In [ ]:
statesAndCapitals.values()

dict_values(['Chennai', 'Mumbai', 'Jaipur', 'Patna'])

In [ ]:
statesAndCapitals.items()

dict_items([('TamilNadu', 'Chennai'), ('Maharashtra', 'Mumbai'), ('Rajasthan', 'Jaipur'), ('Bihar', 'Patna')])

In [ ]:
statesAndCapitals

{'TamilNadu': 'Chennai',
 'Maharashtra': 'Mumbai',
 'Rajasthan': 'Jaipur',
 'Bihar': 'Patna'}

In [ ]:
for state, city in zip(statesAndCapitals.keys(), statesAndCapitals.values()):
  print(f'{state}:{city}')

TamilNadu:Chennai
Maharashtra:Mumbai
Rajasthan:Jaipur
Bihar:Patna

#List Comprehension

In [ ]:
for num in range(1,11):
  print(num**2)

1
4
9
16
25
36
49
64
81
100

In [ ]:
for num in range(1,11):
  squarednumbers = num**2
  print(squarednumbers)

1
4
9
16
25
36
49
64
81
100

In [ ]:
print(squarednumbers)

100

In [ ]:
squarednumbers =  []
for num in range(1,11):
  squarednumbers.append(num**2)
print(squarednumbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
#squarednumbers =  [] #step 1
#squarednumbers =  [expression for loop sequence] #Step 2

squarednumbers =  [num**2 for num in range(1,11)]
squarednumbers

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
squarednumbers =  []
for num in range(1,11):
  if num%2==0:
    squarednumbers.append(num**2)
print(squarednumbers)

[4, 16, 36, 64, 100]

In [ ]:
#squarednumbers =  [] #step 1
#squarednumbers =  [expression for loop sequence] #Step 2
#squarednumbers =  [expression for loop sequence if condition] #Step 3

squarednumbers =  [num**2 for num in range(1,11) if num%2==0]
squarednumbers

[4, 16, 36, 64, 100]

#Remove duplicates from list using for loop

In [ ]:
# using set()
numbers = [1,2,3,4,2,3,4,5,6]
nodup = set(numbers)
nodup

{1, 2, 3, 4, 5, 6}

In [ ]:
#additional list

numbers = [1,2,3,4,2,3,4,5,6]
unique=[]

for num in numbers:
  if num not in unique:
    unique.append(num)
    print(f'{num} added to the unique list')
  else:
    print(f'{num} already in unique list')
unique

1 added to the unique list
2 added to the unique list
3 added to the unique list
4 added to the unique list
2 already in unique list
3 already in unique list
4 already in unique list
5 added to the unique list
6 added to the unique list

[1, 2, 3, 4, 5, 6]

In [ ]:
l1 = [1,2,3,4,5] #iterate
l2= [1,4,5,6,7]
common = []


for num in l1:
  if num in l2 and num not in common:
    common.append(num)

In [ ]:
common

[1, 4, 5]

#Session 8 - Functions

- Built-in functions - ()
- User Defined Function
- Annonymouse function or Lambda function - Map and Filter
- Scope of variables

### Function Definition

- Function without Parameter
def function_name():

  logic here!


### Function Calling

function_name()


- Function with Parameter
def function_name(parameter1, ...paramater2):

  logic here!


### Function Calling

function_name(valueforparamter1 argument1, argument n ...)

In [ ]:
#Function Definition
def intro():
  print("Hello Welcome!")

In [ ]:
intro()

Hello Welcome!

In [ ]:
def introduce(username):
  print("Hello Welcome!",username)

In [ ]:
introduce()

TypeError: introduce() missing 1 required positional argument: 'username'

In [ ]:
def introduce(username,userage):
  print("Hello Welcome!",username,"Age:",userage)

In [ ]:
introduce("Entri",10)

Hello Welcome! Entri Age: 10

In [ ]:
introduce(10,"Entri")

Hello Welcome! 10 Age: Entri

In [ ]:
introduce(userage=10,username="Entri")

Hello Welcome! Entri Age: 10

#Task

- create a functinon called introyou which has the paramerters name and age.
- get input from the user
- print in the below format!
- Enter your name:
- Enter your age:
- Hey name! Welcome! you are age years old!

In [ ]:
def introyou(name,age):
	print(f"hey {name}! welcome! your are {age} years old")

name=input("Enter your Name:")
age=input("Enter your age:")
introyou(name,age)

Enter your Name:Entri
Enter your age:10
hey Entri! welcome! your are 10 years old

## return keyword

In [ ]:
def addfunc(num1, num2):
  add=num1+num2
  return add

result= addfunc(2,3)
result

5

## task

convert that greatest of 2 numbers into a function

enter n1: 5

enter n2: 6

6 is greatest!

In [ ]:
def greaternum (num1,num2):
  return num1 if num1>num2 else num2

greaternum(10,15)

15

In [ ]:
def greatest_of_two(num1, num2):
    if num1> num2:
        return num1
    else:
        return num2

num1 = 5
num2 = 6
result = greatest_of_two(num1, num2)
result

6

#Lambda Function --> Annonymous function

- Used as inline function, quicker taks, non-repetitive task
- it is mostly used along with map and filter

lambda arguments : expression

In [ ]:
def squarenum(n):
  return n**2

In [ ]:
squarenum(2)

4

In [ ]:
squarenum = lambda n : n**2

In [ ]:
squarenum(2)

4

In [ ]:
addnum =  lambda a,b : a+b
addnum(2,3)

5

#Map function

map(function, iterable)

function - can be a built in function or user defined function or lambda function

In [ ]:
numlist = ['1','2','3','4','5']
numlist

['1', '2', '3', '4', '5']

In [ ]:
a='1'
type(a)

str

In [ ]:
a=int(a)
type(a)

int

In [ ]:
list(map(int, numlist))

[1, 2, 3, 4, 5]

In [ ]:
cities = ['chennai','coimbatore','hyderabad','bangalore']
cities=list(map(str.capitalize, cities))

In [ ]:
cities

['Chennai', 'Coimbatore', 'Hyderabad', 'Bangalore']

In [ ]:
nlist = list(range(1,11))
nlist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
squrenlist = list(map(lambda n : n**2, nlist))
squrenlist

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

#Filter

filter ( function, iterable )

In [ ]:
nlist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
for n in nlist:
  if n%2==0:
    print(n)

2
4
6
8
10

In [ ]:
list(filter(lambda n:n%2==0, nlist))

[2, 4, 6, 8, 10]

# task

- using range create a numlist from 1 to 20
- using filter, filter out the odd numbers
- using map, convert the odd number into its cube value

In [ ]:
nlist = list(range(1,21))
nlist

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
oddlist  = list(filter(lambda n:n%2!=0, nlist))
oddlist

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [ ]:
cubelist = list(map(lambda n : n**3, oddlist))
cubelist

[1, 27, 125, 343, 729, 1331, 2197, 3375, 4913, 6859]

#Scope of variable

1. Local Scope
2. Global scope
3. non-local scope

In [ ]:
num=10 #global variable
print("p1 - Number before the function",num) #p1

def calc():
  num=20 #local variable
  print("p2- Number Inside the function",num)#p2

print("p3 - Number after the function",num) #p3

calc()


print("p4 -Number after calling the function",num) #p4

#p1 - 10, p2 - 20, p3 - ?, p4 - ?

p1 - Number before the function 10
p3 - Number after the function 10
p2- Number Inside the function 20
p4 -Number after calling the function 10

In [ ]:
num=10 #global variable
print("p1 - Number before the function",num) #p1

def calc():
  number=20 #local variable
  print("p2- Number Inside the function",number)#p2

num
print("p3 - Number after the function",num) #p3

calc()


print("p4 -Number after calling the function",number) #p4

#p1 - 10, p2 - 20, p3 - ?, p4 - ?

p1 - Number before the function 10
p3 - Number after the function 10
p2- Number Inside the function 20

NameError: name 'number' is not defined

In [ ]:
num=10 #global variable
print("p1- Number before the function",num) #p1

def calc():
  global num #global variable
  num=20
  print("p2- Number Inside the function",num)#p2

print("p3- Number after the function",num) #p3

calc()

print("p4 - Number after calling the function",num) #p4

p1- Number before the function 10
p3- Number after the function 10
p2- Number Inside the function 20
p4 - Number after calling the function 20

In [ ]:
num=10
print("p1- Outside the function",num) #10
def calc():

  num=20
  print("p2 - Inside the function",num) #20
  def inner():
    nonlocal num
    num=30
    print("p3 - Inside the inner function",num) #30

    num=100
  inner()
  print("p4 -Inside the function",num) #100

calc()
print("p5 - Outside the function",num) #10

p1- Outside the function 10
p2 - Inside the function 20
p3 - Inside the inner function 30
p4 -Inside the function 100
p5 - Outside the function 10

#Session 9 File Handling and Exception Handling

## File Handling
Mode!
 - Open
 - Read
 - Write/Append

File open --> Read, write, append
File create

Mode	Description

r	Opens the file for reading (default).

w	Opens the file for writing (overwrites if the file exists).

a	Opens the file for appending (adds to the end of the file if it exists).

r+	Opens the file for both reading and writing.

w+	Opens the file for both writing and reading (overwrites if the file exists).

a+	Opens the file for both appending and reading.

x	Creates a new file. If the file already exists, the operation fails.

t	Text mode (default).

b	Binary mode (used for non-text files like images).

## Method 1 Syntax

file_variable = open(file_path,mode)

file handling operations

Once the file handling operations are over we need to close the file using
file_variable.close()

## Method 2 Syntax


with open(file_path, mode) as file_variable:

  logic

- This syntax will automatically closes the opened file!

#Reading a file!

In [ ]:
file_path="/content/sample.txt"
mode = 'r'
f1 = open(file_path,mode)
content = f1.read()
print(content)
f1.close()

Hi this is a sample file

In [ ]:
with open(file_path, mode) as f1:
  content = f1.read()
  print(content)

Hi this is a sample file

In [ ]:
file_path="/content/sample2.txt" #FileNotFoundError if the file specified is not found!
mode = 'r'
f1 = open(file_path,mode)
content = f1.read()
print(content)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample2.txt'

#Writing into a file - create new file if doesnt exist

In [ ]:
file_path="/content/sample.txt"
mode = 'w' #write mode will overwrites the exising content!
with open(file_path, mode) as f1:
  input_content = "This is a new line added to sample.txt from python code!"
  f1.write(input_content)
  print("Data inserted into the file successfully!")

Data inserted into the file successfully!

In [ ]:
file_path="/content/sample.txt"
mode = 'r'
f1 = open(file_path,mode)
content = f1.read()
print(content)
f1.close()

This is a new line added to sample.txt from python code!

In [ ]:
file_path="/content/sample2.txt" #it will not throw file not found error rather it will create a new file!
mode = 'w' #write mode will overwrites the exising content!
with open(file_path, mode) as f1:
  input_content = "This is a new file created using python write mode! and this data is also inserted in this file!"
  f1.write(input_content)
  print("Data inserted into the file successfully!")

Data inserted into the file successfully!

In [ ]:
file_path="/content/sample2.txt" #it will not throw file not found error rather it will create a new file!
mode = 'a' #write mode will overwrites the exising content!
with open(file_path, mode) as f1:
  input_content = "\nThis is second line using python code!"
  f1.write(input_content)
  print("Data inserted into the file successfully!")

Data inserted into the file successfully!

In [ ]:
file_path="/content/sample2.txt"
mode = 'r'
f1 = open(file_path,mode)
content = f1.read()
print(content)
f1.close()

This is a new file created using python write mode! and this data is also inserted in this file!
This is second line using python code!

In [ ]:
file_path="/content/sample2.txt" #it will not throw file not found error rather it will create a new file!
mode = 'a' #write mode will overwrites the exising content!
with open(file_path, mode) as f1:
  input_content = "This is next line -------!!!!!"
  f1.write(input_content)
  print("Data inserted into the file successfully!")

Data inserted into the file successfully!

In [ ]:
file_path="/content/sample2.txt"
mode = 'r'
f1 = open(file_path,mode)
content = f1.read()
print(content)
f1.close()

This is a new file created using python write mode! and this data is also inserted in this file!
This is second line using python code!This is next line -------!!!!!

In [ ]:
file_path="/content/sample3.txt" #it will not throw file not found error rather it will create a new file!
mode = 'a' #write mode will overwrites the exising content!
with open(file_path, mode) as f1:
  input_content = "This is next line -------!!!!!"
  f1.write(input_content)
  print("Data inserted into the file successfully!")

Data inserted into the file successfully!

#Task

You need get the details of student and store it in a file!

Some of the details can include name, age, city! ( make sure to get the data from the user)

also get the file name to be stored and content to be stored inside the file from the user!

In [ ]:
name = input("Enter student's name: ")
age = input("Enter student's age: ")
city = input("Enter student's city: ")
filename = input('Student file name:')
content =( f"Name: {name}\nAge: {age}\nCity: {city}")
with open(filename, "w") as file:
    file.write(content)

Enter student's name: Entri
Enter student's age: 10
Enter student's city: Kerala
Student file name:student.txt

#Exception Handling

run time errors (Exceptions) can be handled with code!

Exception Handling?

If we have a code and it causes an error then the entire program execution will get interrupted!



- try block - We are going to write the code which may cause an Exception (error)!

- except block - in case error occurred what do? we can mention it here!

  - We can mention what type of error we may get
  - if more number of errors can occur you can create for each one
  - we dont know what type of error will come we can directly use Exception class will give you the what error occurred?

- else block - in case no error means what code i need to run!

- finally block - you can put the ***code*** here which must run when there is an error or no error occurred!

#Code without Exception Handling

In [ ]:
file_path="/content/sample10.txt"
mode = 'r'
print("this is another logic")
f1 = open(file_path,mode)
content = f1.read()
print(content)
f1.close()
print("This code has to be executed no matter what!")
print("this is another logic")

this is another logic

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample10.txt'

#Code with Exception Handling

In [ ]:
file_path="/content/sample10.txt"
mode = 'r'

try:
  f1 = open(file_path,mode)
  content = f1.read()
except FileNotFoundError: #in case if the file is not found
  print("The mentioned file is not found!")
else: #in case if the file is found
  print(content)
finally: # it will run if exception occurred or not!
  print("This code has to be executed no matter what!")


print("this is another logic")

The mentioned file is not found!
This code has to be executed no matter what!
this is another logic

In [ ]:
file_path="/content/sample10.txt"
mode = 'r'

try:
  f1 = open(file_path,mode)
  content = f1.read()
except Exception as e: #in case if the file is not found
  print("Some error occurred:",e)
else: #in case if the file is found
  print(content)
finally: # it will run if exception occurred or not!
  print("This code has to be executed no matter what!")


print("this is another logic")

Some error occurred: [Errno 2] No such file or directory: '/content/sample10.txt'
This code has to be executed no matter what!
this is another logic

In [ ]:
file_path="/content/sample10.txt"
mode = 'r'

try:
  f1 = open(file_path,mode)
  content = f1.read()
except FileNotFoundError: #in case if the file is not found
  print("The mentioned file is not found!")
except ValueError: #in case if the file is not found
  print("There is a value error!")
else: #in case if the file is found
  print(content)
finally: # it will run if exception occurred or not!
  print("This code has to be executed no matter what!")


print("this is another logic")

#File Menu program

- Menu
  - 1. Create a file ( write )
  - 2. Read a file
  - 3. update a file ( append )
  - 4. exit

Sample output:

 File Menu
  1. Create a file ( write )
  2. Read a file
  3. update a file ( append )
  4. exit

  Enter your choice: 1

  create a file function to be exectuted

  Enter your choice: 2

  read the file

  Enter your choice:4

  thank you!


how to make the user to enter the choice again and again?

If 4 is clicked how to stop the program?

In [ ]:
def createfile():
  filename = input('Enter the file name:')
  content =input('Enter the data:')
  with open(filename, "w") as file:
      file.write(content)
      print("File created successfully!")

In [ ]:
def readfile():
  filename = input('Enter the file name:')
  mode = 'r'

  try:
    f1 = open(filename,mode)
    content = f1.read()
  except FileNotFoundError: #in case if the file is not found
    print("The mentioned file is not found!")
  except ValueError: #in case if the file is not found
    print("There is a value error!")
  else: #in case if the file is found
    print(content)

In [ ]:
def appendfile():
  print("Implement this function yourself!")

In [ ]:
def menu():
  print("1.Create a file\n2.Read a file\n3.Update a file\n4.Exit")
  while True:
    try:
      choice = int(input("Enter the choice:"))
      if choice == 1:
        createfile()
      elif choice == 2:
        readfile()
      elif choice == 3:
        appendfile()
      elif choice == 4:
        print("Thank you")
        break
      else:
        print("Enter the choice between 1 to 4")
    except Exception as e:
      print("Some error occurred!",e)

In [ ]:
menu()

1.Create a file
2.Read a file
3.Update a file
4.Exit
Enter the choice:1
Enter the file name:pythonfile.txt
Enter the data:this is menu created file
File created successfully!
Enter the choice:r
Some error occurred! invalid literal for int() with base 10: 'r'
Enter the choice:2
Enter the file name:javafile.txt
The mentioned file is not found!
Enter the choice:pythonfile.txt
Some error occurred! invalid literal for int() with base 10: 'pythonfile.txt'
Enter the choice:2
Enter the file name:pythonfile.txt
The mentioned file is not found!
Enter the choice:4
Thank you

In [ ]:
menu()

1.Create a file
2.Read a file
3.Update a file
4.Exit
Enter the choice:2
Enter the file name:pythonfile.txt
this is menu created file
Enter the choice:4
Thank you

#Session 10 - Modules and Intro to OOPS

In [ ]:
intro("Entri")

NameError: name 'intro' is not defined

#Modules


Module is a python file which may contain 1 or more functions that can be imported and used!

import modulename

from modulename import functionname

import modulename as shortcutname

Create a Google colab notebook

Create all the functionalities that you might need later

download it as .py File --> Download --> filename.py

Come to the notebook where you might need that function

there you need to upload the .py file which you downloaded earlier

then you can use the import modulename ( filename of that .py file)

then you can start using the functionalities

## Library

Lets say if you need more such modules

you can put them in a folder and create a python file called __init__.py this makes that folder a package called as library.

!pip install git+urlofthegit

In [ ]:
import mynewmodule

In [ ]:
mynewmodule.intro("Arun")

Hello Arun

In [ ]:
import mynewmodule as mnm

In [ ]:
mnm.add(10,20)

30

In [ ]:
mnm.intro("Maha")

Hello Maha

In [ ]:
from mynewmodule import add

In [ ]:
add(1,2)

3

# task
calculator.py
Create your version calculator python program

- addition
- subtraction
- mulitplication
- division
- floor division
- remainder
- sqrt
- square of a number


calctest

- import the calculator module

- call the add function

#Introduction to Object Oriented Programming

- Programming Paradigm
- Classes and Objects are the main concepts in a OOP program
- JAVA 100% OOP, Python - hybrid ( both procedural and OOP )

In [ ]:
name="Entri" #predfined data type
print(type(name)) #name it is of class 'str' type - data type - str

<class 'str'>

In [ ]:
name.lower()

'entri'

In [ ]:
name.upper()

'ENTRI'

if name="Entri" belongs to a str class and also we can able to access all the functionlities inside that class! and we call it as String type! so it is a data type!

If so, if we can able to create a class and bunch of functionlities then can we able to tell this as a user defined data type?

#Class and Object

Class is a blueprint we can able to create as much instances or objects we want to create using that blueprint!

A class will contain behaviours (functionalites often called method) and attributes ( variables )

If we can able to create an instance for this class that is called as object

This object can able to access the  behaviours (functionalites often called method) and attributes ( variables ) of that class!

#Class Syntax:


class ClassName:
- behaviours

- attributes

#Object Syntax:

objectname = ClassName()

##class creation

In [ ]:
class SampleClass:
  sampledata="Data"

  def samplefunc(self):
    print("this is a sample function created inside the Sample class!!!")

##Object Creation

In [ ]:
obj1 = SampleClass()

##accessing behaviours and attributes with object

In [ ]:
obj1.sampledata

'Data'

In [ ]:
obj1.samplefunc()

this is a sample function created inside the Sample class!!!

In [ ]:
print(type(obj1)) #user defined data type -- Sample Class

<class '__main__.SampleClass'>

#class which requirs some details

If we require some details for creating the object then we can specify that in the constructor __init__(self,somedetails)

In [ ]:
class Student:
  #constructor -- it constructs the memory for any object!
  def __init__(self,name,age):
    print("Name:",name)

  def printdetails(self):
    print("Student Details:")
    print(f"Name:{name} age:{age}")

In [ ]:
s1 = Student()

TypeError: Student.__init__() missing 2 required positional arguments: 'name' and 'age'

In [ ]:
s1 = Student("Raj",11)

Name: Raj

In [ ]:
s1.printdetails() #since name and age are part of the constructor which a function so those variables are local variables!

In [ ]:
class Student:
  #constructor -- it constructs the memory for any object!
  def __init__(self,name,age):
    self.username = name
    self.userage = age
    #print("Name:",name)

  def printdetails(self):
    print("Student Details:")
    print(f"Name:{self.username} age:{self.userage}")

In [ ]:
s1=Student("Kiran",20)

In [ ]:
s1.printdetails()

Student Details:
Name:Kiran age:20

In [ ]:
s2=Student("Suresh",18)

In [ ]:
s2.printdetails()

Student Details:
Name:Suresh age:18

#task

Create a class called Human

Create some behaviours of humans lets say read, write, eat, walk just have print statements

then create an instance for the Human class let the instance be you!

Make sure to get the name and age while creating the instance!

In [ ]:
class Human:
  def __init__(self, name, age):
    self.name=name
    self.age=age

  def read(self):
    print(f"{self.name} is reading a book.")

  def eat(self):
    print(f"{self.name} is eating.")

  def walk(self):
    print(f"{self.name} is walking")

  def printdetails(self):
        print("Human Details:")
        print(f"Name: {self.name}, Age: {self.age}")

In [ ]:
h1 = Human("Shankar",20)

In [ ]:
h1.read()

Shankar is reading a book.

In [ ]:
h1.eat()

Shankar is eating.

In [ ]:
h1.walk()

Shankar is walking

In [ ]:

h1.printdetails()

Human Details:
Name: Shankar, Age: 20

#Session 11: OOPS Properties

- Inheritance
- Ploymorphism
- Encapsulation
- Abstraction

#Smartphone

Features ( Functionalities )
- Apps
- OS
- Internet Connectivity
- Calling
- RAM / Storage
- Camera
- High Battery capacity
- AI
- WIFI
- Bluetooth
- Touch Screen

Brands - Brands can have its own features + if it is inheriting Smartphone then it can also access all the features ( Functionalities ) inside the Smartphone class

- OPPO
- Samsung
- Vivo
- POCO
- Redmi
- Realme

In [ ]:
class SmartPhone:
  def features(self):
    print("Smartphone Features installed!")

  def Wifi(self):
    print("Wifi Feature now activated!")

  def Apps(self):
    print("Apps can be installed now!!")

In [ ]:
sm1 = SmartPhone()

In [ ]:
sm1.Apps()

Apps can be installed now!!

In [ ]:
sm1.features()

Smartphone Features installed!

In [ ]:
sm1.Wifi()

Wifi Feature now activated!

In [ ]:
class OPPO:
  def newmodelfeatures(self):
    print("OPPO's unique features installed!")

  def ultrahdcam(self):
    print("Ultra HD Cam activated!")

In [ ]:
opmod1 =  OPPO()

In [ ]:
opmod1.newmodelfeatures()

OPPO's unique features installed!

In [ ]:
opmod1.ultrahdcam()

Ultra HD Cam activated!

#Inheritance

In [ ]:
class OPPO(SmartPhone): #inherting Smartphone class
  def newmodelfeatures(self):
    print("OPPO's unique features installed!")

  def ultrahdcam(self):
    print("Ultra HD Cam activated!")

OPPO(SmartPhone)

SmartPhone- **Base Class** / Parent Class / Main class

OPPO - **Derived Class** / Child Class / Sub class

In [ ]:
opmod1 =  OPPO()

In [ ]:
opmod1.features()

Smartphone Features installed!

In [ ]:
opmod1.Wifi()

Wifi Feature now activated!

In [ ]:
opmod1.ultrahdcam()

Ultra HD Cam activated!

- SIngle Inheritance - 1 base class
- Multiple Inheritance - more than 1 base class

In [ ]:
class Network5g:
  def networkupdate(self):
    print("this model is now activatd with 5G technology")

In [ ]:
class OPPO(SmartPhone,Network5g): #Multiple Inheritance
  def newmodelfeatures(self):
    print("OPPO's unique features installed!")

  def ultrahdcam(self):
    print("Ultra HD Cam activated!")

In [ ]:
opmod2 = OPPO()

In [ ]:
opmod2.networkupdate()

this model is now activatd with 5G technology

class A:


clas B(A) - Single Inheritance


class C(B) - Multi Level inheritance


class C can able to access features of both class A and B

#task:

Create a class called Vehcile and have some features

then create another called Car and have some features inherit the above class accordingly.

create an object and access features from both the classes!

In [ ]:
class Vehicle():
  def startengine(self):
    print("Engine has started")

class Car(Vehicle):
  def carstart(self):
    print("Car has started to ride")

car1=Car()
car1.carstart()
car1.startengine()

Car has started to ride
Engine has started

#Polymorphism

- many - forms

In [ ]:
class DataCleaner:
  def clean(self,data):
    print(f"General Data Cleaning exected on the given Data {data}")

  def cleanercheck(self):
    print("Cleaner Check started!...")

In [ ]:
class NumericalDataCleaner(DataCleaner):
  def clean(self,data):

    print(f"Numerical Data Cleaning exected on the given Data {data}")

In [ ]:
dc1=NumericalDataCleaner()

In [ ]:
dc1.clean("Sample data")

Numerical Data Cleaning exected on the given Data Sample data

In [ ]:
class NumericalDataCleaner(DataCleaner):
  def clean(self,data):
    super().clean("sample data")
    print(f"Numerical Data Cleaning exected on the given Data {data}")

In [ ]:
dc2=NumericalDataCleaner()
dc2.clean("Sample data")

General Data Cleaning exected on the given Data sample data
Numerical Data Cleaning exected on the given Data Sample data

#Duck Typing

In [ ]:
class DSLRCam:
  def click_pic(self):
    print("Capturing pic using DSLR")

In [ ]:
class PhoneCam:
  def click_pic(self):
    print("Capturing pic using Phone!")

In [ ]:
dslrobj = DSLRCam()
phonobj = PhoneCam()

In [ ]:
dslrobj.click_pic()

Capturing pic using DSLR

In [ ]:
phonobj.click_pic()

Capturing pic using Phone!

In [ ]:
devices = [DSLRCam(),PhoneCam()]
for device in devices:
  device.click_pic()

Capturing pic using DSLR
Capturing pic using Phone!

#Encapsulation

- Access modifiers - public, protected _ , private __
- Hiding some essential features using getters and setters we are going to access the hidden features this is for security enhancement!
- create variable called name - it is a public variable
- _age - protected mode - it is visible within the class and its subclass
- __phonenumber - private ( double underscore before the variable) - this attribute is hidden to the outside classes!
- using getters and setters we can access or modify the __phonenumber

In [ ]:
class Student:
  def __init__(self,name,marks):
    self.studentname= name #public variable
    self.__studentmarks = marks #protected variable - hidden from other classes

  def details(self): #getter
    print(f"Welcome {self.studentname} your marks {self.__studentmarks}")

In [ ]:
s1 = Student("Malathi",98)

In [ ]:
s1.details()

Welcome Malathi your marks 98

In [ ]:
s1.studentname

'Malathi'

In [ ]:
s1.__studentmarks #directly we cannot access this variable since it is a private variable

AttributeError: 'Student' object has no attribute '__studentmarks'

In [ ]:
s1.studentname = "Shankar"

In [ ]:
s1.details()

Welcome Shankar your marks 98

#Abstraction

In [ ]:
from abc import ABC, abstractmethod

In [ ]:
class Sample(ABC): # abstract class creation
  def normalfunc(self):
    print("this is a normal function")

In [ ]:
s1 = Sample()

In [ ]:
s1.normalfunc()

this is a normal function

In [ ]:
class Sample(ABC): # abstract class creation
  def normalfunc(self):
    print("this is a normal function")

  @abstractmethod
  def functinA(self):
    print("this is an Abstract method")

In [ ]:
s2 = Sample()

TypeError: Can't instantiate abstract class Sample with abstract method functinA

In [ ]:
class Sample(ABC): # abstract class creation
  def normalfunc(self):
    print("this is a normal function")

  @abstractmethod
  def functinA(self):
    pass

  @abstractmethod
  def functionB(self):
    pass

lets assume we are creating a login screen for an app.

in that it is suggested or mandatory to create certain functionalities

ex: username checking, password checking, change password!

In [ ]:
class New(Sample):
  def newclassfunction(self):
    print("this is inherited class from Abstract Class Sample!")

In [ ]:
obj1 = New() #throws error because this class expected to explain about the abstract method mentioned in its base class

TypeError: Can't instantiate abstract class New with abstract methods functinA, functionB

In [ ]:
class New(Sample): # concrete class - means the class which is implementing the unimplmented abstract method
  def newclassfunction(self):
    print("this is inherited class from Abstract Class Sample!")


  def functinA(self):
    print("this is an Abstract method 1 ")


  def functionB(self):
    print("this is an Abstract method2 ")

In [ ]:
obj1 = New()

In [ ]:
obj1.functinA()

this is an Abstract method 1

#Session 12 - NumPy - NumPy Arrays, Array Operations and functions

- Numerical Python - https://numpy.org/devdocs/user/absolute_beginners.html

- similar to list but it is an array
- perform mathematical operations
- this is foundation for many advanced libraries such as Pandas, matplotlib, Scipy
- n-dimensional arrays - 1D, 2D, 3D - type is ndarray
- Random number generation
- Memory efficient
- Single data type


- Library means collection of modules

--> Folder mylibrary --> module1.py ( set of functions ), module2.py ( set of functions ), then also have __init__.py.

In [ ]:
#!pip install numpy

In [ ]:
import numpy as np

#1D, 2D, 3D arrays

np.array(object, dtype)

#Creating 1D arrays

In [ ]:
arr1d = np.array([1,2,3,4])
arr1d

array([1, 2, 3, 4])

In [ ]:
type(arr1d)

numpy.ndarray

In [ ]:
arr1d.ndim

1

In [ ]:
arr1d.shape # (numberofelements,)

(4,)

In [ ]:
arr1d.size

4

#Creating 2D arrays

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr2d)

[[1 2 3]
 [4 5 6]]

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.shape #(3, 3) - (row,col)

(3, 3)

In [ ]:
arr2d.size

9

#Creating 3D array

![image.png]()

In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3d.shape #(2, 3, 3) - ( depth/layers, row, col)

(3, 3, 3)

#Array initialization techniques

- create arrays using
  - zeros
  - ones
  - specific value
  - random numbers - rand 0-1, randint specific range
  - arange
  - linspace

In [ ]:
arrzeros = np.zeros(5)
arrzeros

array([0., 0., 0., 0., 0.])

In [ ]:
arrzeros = np.zeros(5,dtype=int)
arrzeros

array([0, 0, 0, 0, 0])

In [ ]:
arrzeros.shape

(5,)

In [ ]:
arrzeros.size

5

In [ ]:
arrzeros = np.zeros([2,2],dtype=int)
arrzeros

array([[0, 0],
       [0, 0]])

In [ ]:
arrzeros = np.zeros([2,3,3],dtype=int)
arrzeros

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
arrzeros = np.ones([2,3,3],dtype=int)
arrzeros

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
#using specific numbers - full()
arr100= np.full((2,2,2),100)
arr100

array([[[100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100]]])

#Creating arrays using random numbers

In [ ]:
arrrand = np.random.rand(2,2) #0 to 1
arrrand

array([[0.0411305 , 0.10970838],
       [0.54553916, 0.41951425]])

In [ ]:
arrrandint = np.random.randint(1,100,10)
arrrandint

array([11, 24, 35, 92, 56, 35, 17, 66,  2, 14])

In [ ]:
arrrandint = np.random.randint(1,100,(3,3))
arrrandint

array([[63, 72, 34],
       [49, 20, 35],
       [82, 72, 44]])

In [ ]:
# 2,2 --> 3 arrays -
arrrandint = np.random.randint(1,100,(3,2,2))
arrrandint

array([[[20, 51],
        [75,  4]],

       [[ 2, 77],
        [68,  3]],

       [[35, 55],
        [62, 64]]])

In [ ]:
arrarange = np.arange(1,10)
arrarange

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arrlinspace = np.linspace(1,20,5)
arrlinspace

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
5.75 - 1

4.75

In [ ]:
10.5 - 5.75

4.75

In [ ]:
20 - 15.25

4.75

In [ ]:
arrlinspace = np.linspace(1,10,6)
arrlinspace

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

#Task:

Create a numpy array called calories which will contain everyday calorie intake by a person for a week. (1500, 2500)

In [ ]:
calories= np.random.randint(1500,2500,7)
calories

array([2379, 2135, 2191, 2288, 1679, 1511, 1932])

In [ ]:
calories4wks= np.random.randint(1500,2500,(4,7))
calories4wks

array([[2247, 1705, 1757, 1672, 2426, 2399, 2018],
       [2451, 2332, 2336, 1967, 1809, 2102, 2132],
       [2377, 1978, 2170, 1807, 1895, 2012, 1992],
       [2366, 1930, 1799, 1924, 2073, 1665, 1965]])

#Array Slicing

#1D array slicing

similar to list

[start:stop:step]

In [ ]:
calories.ndim

1

In [ ]:
calories

array([2379, 2135, 2191, 2288, 1679, 1511, 1932])

In [ ]:
calories[:3]

array([2379, 2135, 2191])

In [ ]:
calories[-3]

np.int64(1679)

In [ ]:
calories[-3:]

array([1679, 1511, 1932])

#2D array slicing

shape of 2D array - (rows,cols)

[row_start:row_stop , col_start:col_stop]

In [ ]:
calories4wks.ndim

2

In [ ]:
calories4wks.shape

(4, 7)

In [ ]:
calories4wks

array([[2247, 1705, 1757, 1672, 2426, 2399, 2018],
       [2451, 2332, 2336, 1967, 1809, 2102, 2132],
       [2377, 1978, 2170, 1807, 1895, 2012, 1992],
       [2366, 1930, 1799, 1924, 2073, 1665, 1965]])

In [ ]:
calories4wks[0]

array([2247, 1705, 1757, 1672, 2426, 2399, 2018])

In [ ]:
calories4wks[-1]

array([2366, 1930, 1799, 1924, 2073, 1665, 1965])

In [ ]:
#[row_start:row_stop , col_start:col_stop]
calories4wks[:2,:2 ]

array([[2247, 1705],
       [2451, 2332]])

In [ ]:
calories4wks[:,-3:]

array([[2426, 2399, 2018],
       [1809, 2102, 2132],
       [1895, 2012, 1992],
       [2073, 1665, 1965]])

#3d array slicing

3D array shape - depth,rows,cols

[depthstart:depthstop, rowstart:row_stop, colstart:colstop]

In [ ]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
arr3d[0:2, :2,:2]

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

#Array Operations

In [ ]:
a =[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [ ]:
a = np.array(a)
b = np.array(b)
a+b

array([5, 7, 9])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

#Boolean Indexing

In [ ]:
calories > 2000

array([ True,  True,  True,  True, False, False, False])

In [ ]:
calories[calories > 2000]

array([2379, 2135, 2191, 2288])

In [ ]:
np.sum(calories)

np.int64(14115)

In [ ]:
np.mean(calories)

np.float64(2016.4285714285713)

In [ ]:
np.min(calories)

np.int64(1511)

In [ ]:
np.argmin(calories)

np.int64(5)

In [ ]:
np.max(calories)

np.int64(2379)

In [ ]:
np.argmax(calories)

np.int64(0)

#reshape

In [ ]:
ar=np.arange(24)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b=ar.reshape(4,6) # reshape(no of rows, no of cols)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
b=ar.reshape(2, 2,6) # reshape(no of rows, no of cols)
b

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

#Session 13 - Pandas

**Introduction**

Pandas is an open-source Python library used for data manipulation and analysis. It provides powerful data structures, primarily Series (1D) and DataFrame (2D), making it easy to work with structured data like tables (Excel, SQL, CSV, etc.).


https://pandas.pydata.org/docs/user_guide/10min.html


Why Use Pandas?
- Easy to clean, transform, and analyze data
- Handles missing data efficiently
- Supports reading/writing from multiple formats (CSV, Excel, JSON, SQL)
- Provides powerful aggregation, filtering, and transformation operations
- Works well with NumPy and integrates seamlessly with visualization libraries like Matplotlib & Seaborn

In [ ]:
import numpy as np
import pandas as pd

## Pandas Series

A Series is like a column in a table or an array with an index.


pd.Series(data, index=None, dtype=None, name=None)

- data: Iterable, dictionary, or scalar value
- index: Custom index labels
- dtype: Data type of the Series
- name: Name of the Series

In [ ]:
data = [10,20,30,40]
data

[10, 20, 30, 40]

In [ ]:
s1 = pd.Series(data)
s1

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
print(type(s1))

<class 'pandas.core.series.Series'>

In [ ]:
index_labels =['a','b','c','d']
s2 = pd.Series(data, index=index_labels,name="Sample Series")
s2

a    10
b    20
c    30
d    40
Name: Sample Series, dtype: int64

In [ ]:
print(type(s2))

<class 'pandas.core.series.Series'>

in Series and DataFrame the data type looks like int64, float64, object

In [ ]:
s3 = pd.Series(data, index=index_labels,dtype='float64',name="Sample Series")
s3

a    10.0
b    20.0
c    30.0
d    40.0
Name: Sample Series, dtype: float64

In [ ]:
data = {'k1':'v1','k2':'v2','k3':'v3'}
data

{'k1': 'v1', 'k2': 'v2', 'k3': 'v3'}

In [ ]:
s4 = pd.Series(data)
s4

k1    v1
k2    v2
k3    v3
dtype: object

In [ ]:
s5 = pd.Series(range(0,10))
s5

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [ ]:
nparr = np.array([1,2,3,4])

numser = pd.Series(nparr)
numser

0    1
1    2
2    3
3    4
dtype: int64

#Accessing elements of the Series

In [ ]:
movies_dict = {
    "The Avengers (2012)": 8.0,
    "Avengers: Age of Ultron (2015)": 7.3,
    "Avengers: Infinity War (2018)": 8.4,
    "Avengers: Endgame (2019)": 8.4,
    "Captain America: Civil War (2016)": 7.8,
    "Thor: Ragnarok (2017)": 7.9,
    "Iron Man (2008)": 7.9,
    "Guardians of the Galaxy (2014)": 8.0,
    "Spider-Man: No Way Home (2021)": 8.3,
    "Black Panther (2018)": 7.3
}
movieseries = pd.Series(movies_dict,name='IMDB Rating')
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             8.4
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries.index

Index(['The Avengers (2012)', 'Avengers: Age of Ultron (2015)',
       'Avengers: Infinity War (2018)', 'Avengers: Endgame (2019)',
       'Captain America: Civil War (2016)', 'Thor: Ragnarok (2017)',
       'Iron Man (2008)', 'Guardians of the Galaxy (2014)',
       'Spider-Man: No Way Home (2021)', 'Black Panther (2018)'],
      dtype='object')

In [ ]:
movieseries.values

array([8. , 7.3, 8.4, 8.4, 7.8, 7.9, 7.9, 8. , 8.3, 7.3])

In [ ]:
movieseries.shape

(10,)

In [ ]:
movieseries.size

10

In [ ]:
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             8.4
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries['The Avengers (2012)']

np.float64(8.0)

#using loc and iloc

In [ ]:
movieseries.loc['The Avengers (2012)']

np.float64(8.0)

In [ ]:
movieseries[0]

<ipython-input-22-d99177b9cd61>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movieseries[0]

np.float64(8.0)

In [ ]:
movieseries.iloc[0]

np.float64(8.0)

In [ ]:
movieseries.loc[['The Avengers (2012)','Avengers: Endgame (2019)']]

The Avengers (2012)         8.0
Avengers: Endgame (2019)    8.4
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries.iloc[[0,-1]]

The Avengers (2012)     8.0
Black Panther (2018)    7.3
Name: IMDB Rating, dtype: float64

#boolean based indexing

In [ ]:
movieseries > 8.0

The Avengers (2012)                  False
Avengers: Age of Ultron (2015)       False
Avengers: Infinity War (2018)         True
Avengers: Endgame (2019)              True
Captain America: Civil War (2016)    False
Thor: Ragnarok (2017)                False
Iron Man (2008)                      False
Guardians of the Galaxy (2014)       False
Spider-Man: No Way Home (2021)        True
Black Panther (2018)                 False
Name: IMDB Rating, dtype: bool

In [ ]:
movieseries [movieseries > 8.0]

Avengers: Infinity War (2018)     8.4
Avengers: Endgame (2019)          8.4
Spider-Man: No Way Home (2021)    8.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries['Avengers: Endgame (2019)'] = 9.0

In [ ]:
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries['New Marvel Movie']

KeyError: 'New Marvel Movie'

In [ ]:
movieseries['New Marvel Movie'] = 8
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
New Marvel Movie                     8.0
Name: IMDB Rating, dtype: float64

#remove the data using drop

inplace=false

In [ ]:
movieseries.drop('New Marvel Movie') #drop the data and returns a new series

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
New Marvel Movie                     8.0
Name: IMDB Rating, dtype: float64

In [ ]:
newseries = movieseries.drop('New Marvel Movie')
newseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
New Marvel Movie                     8.0
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries.drop('New Marvel Movie',inplace=True) #this will remove the data from this series itself and does not return a new series

In [ ]:
movieseries

The Avengers (2012)                  8.0
Avengers: Age of Ultron (2015)       7.3
Avengers: Infinity War (2018)        8.4
Avengers: Endgame (2019)             9.0
Captain America: Civil War (2016)    7.8
Thor: Ragnarok (2017)                7.9
Iron Man (2008)                      7.9
Guardians of the Galaxy (2014)       8.0
Spider-Man: No Way Home (2021)       8.3
Black Panther (2018)                 7.3
Name: IMDB Rating, dtype: float64

In [ ]:
movieseries['Average Rating'] = movieseries.mean()
movieseries

The Avengers (2012)                  8.00
Avengers: Age of Ultron (2015)       7.30
Avengers: Infinity War (2018)        8.40
Avengers: Endgame (2019)             9.00
Captain America: Civil War (2016)    7.80
Thor: Ragnarok (2017)                7.90
Iron Man (2008)                      7.90
Guardians of the Galaxy (2014)       8.00
Spider-Man: No Way Home (2021)       8.30
Black Panther (2018)                 7.30
Average Rating                       7.99
Name: IMDB Rating, dtype: float64

# DataFrame

A DataFrame is a table-like structure with rows and columns (similar to Excel or SQL tables).

Syntax:

df = pd.DataFrame(
    data,
    index=index_labels,
    columns=column_labels,
    dtype=data_type,
    copy=bool_value
)

**Explanation of Parameters**

- data → The actual data stored in the DataFrame. It can be:
A dictionary of lists or dictionaries, A list of lists (2D list), A NumPy array
A Pandas Series, Another DataFrame

- index (optional) → A list of row labels (default: 0,1,2,...)
If not provided, Pandas assigns numeric indices automatically.

- columns (optional) → A list of column labels (default: extracted from data).
If provided, it renames the columns.

- dtype (optional) → Specifies the data type for all columns (e.g., float, int, str). If omitted, Pandas automatically infers the data type.

- copy (optional, default: False) → If True, creates a copy of the input data rather than modifying the original data.

In [ ]:
data = [[1,2,3],[4,5,6],[7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
df1 = pd.DataFrame(data)
df1

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df1.shape

(3, 3)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
 2   2       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [ ]:
data = {
    "Name": ["Iron Man", "Thor", "Hulk", "Captain America"],
    "Movie": ["Avengers", "Thor: Ragnarok", "Hulk", "Avengers"],
    "IMDB_Rating": [8.0, 7.9, 6.7, 8.1]
    #Name, Movie, IMDB_Rating becomes column index
}

df2= pd.DataFrame(data)
df2

              Name           Movie  IMDB_Rating
0         Iron Man        Avengers          8.0
1             Thor  Thor: Ragnarok          7.9
2             Hulk            Hulk          6.7
3  Captain America        Avengers          8.1

In [ ]:
data = {
    "Name": ["Iron Man", "Thor", "Hulk", "Captain America"],
    "Movie": ["Avengers", "Thor: Ragnarok", "Hulk", "Avengers"],
    "IMDB_Rating": [8.0, 7.9, 6.7, 8.1]
    #Name, Movie, IMDB_Rating becomes column index
}
index_labels=['C1','C2','C3','C4']
df2= pd.DataFrame(data, index=index_labels)
df2

               Name           Movie  IMDB_Rating
C1         Iron Man        Avengers          8.0
C2             Thor  Thor: Ragnarok          7.9
C3             Hulk            Hulk          6.7
C4  Captain America        Avengers          8.1

In [ ]:
data = [
    ["Iron Man", "Avengers", 8.0],
    ["Thor", "Thor: Ragnarok", 7.9],
    ["Hulk", "Hulk", 6.7],
    ["Captain America", "Avengers", 8.1]
]
column_lables = ['Name','Movie','Rating']
index_labels=['C1','C2','C3','C4']
df2= pd.DataFrame(data, index=index_labels,columns=column_lables)
df2

               Name           Movie  Rating
C1         Iron Man        Avengers     8.0
C2             Thor  Thor: Ragnarok     7.9
C3             Hulk            Hulk     6.7
C4  Captain America        Avengers     8.1

In [ ]:
samplecol = df2['Movie'] #single column
samplecol

C1          Avengers
C2    Thor: Ragnarok
C3              Hulk
C4          Avengers
Name: Movie, dtype: object

In [ ]:
print(type(samplecol))

<class 'pandas.core.series.Series'>

In [ ]:
nparr = np.array([[1,2,3],[4,5,6],[7,8,9]])
nparr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df3 = pd.DataFrame(nparr) #copy=False
df3

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df3.iloc[0,0]

np.int64(1)

In [ ]:
df3.iloc[0,0] = 100
df3

     0  1  2
0  100  2  3
1    4  5  6
2    7  8  9

In [ ]:
nparr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
df3 = pd.DataFrame(nparr,copy=True) #copy=True
df3

     0  1  2
0  100  2  3
1    4  5  6
2    7  8  9

In [ ]:
nparr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
df3.iloc[0,0] = 500
df3

     0  1  2
0  500  2  3
1    4  5  6
2    7  8  9

In [ ]:
nparr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
tamil_movies = {
    "Movie Name": ["Vikram", "Ponniyin Selvan", "Master", "Karnan", "Kaithi"],
    "Director": ["Lokesh Kanagaraj", "Mani Ratnam", "Lokesh Kanagaraj", "Mari Selvaraj", "Lokesh Kanagaraj"],
    "Duration (mins)": [175, 167, 178, 152, 145],
    "Hero": ["Kamal Haasan", "Vikram", "Vijay", "Dhanush", "Karthi"],
    "Movie Rating": [8.4, 7.8, 7.3, 8.2, 8.5],
    "Revenue Collected (Crores)": [450, 500, 300, 110, 105]
}

moviedf= pd.DataFrame(tamil_movies)
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Movie Name                  5 non-null      object
 1   Director                    5 non-null      object
 2   Duration (mins)             5 non-null      int64
 3   Hero                        5 non-null      object
 4   Movie Rating                5 non-null      float64
 5   Revenue Collected (Crores)  5 non-null      int64
dtypes: float64(1), int64(2), object(3)
memory usage: 372.0+ bytes

In [ ]:
moviedf.columns

Index(['Movie Name', 'Director', 'Duration (mins)', 'Hero', 'Movie Rating',
       'Revenue Collected (Crores)'],
      dtype='object')

In [ ]:
moviedf['Hero'] #

0    Kamal Haasan
1          Vikram
2           Vijay
3         Dhanush
4          Karthi
Name: Hero, dtype: object

In [ ]:
moviedf.shape

(5, 6)

In [ ]:
moviedf[['Movie Name','Hero']]

        Movie Name          Hero
0           Vikram  Kamal Haasan
1  Ponniyin Selvan        Vikram
2           Master         Vijay
3           Karnan       Dhanush
4           Kaithi        Karthi

In [ ]:
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf[0]

KeyError: 0

In [ ]:
moviedf.iloc[0]

Movie Name                              Vikram
Director                      Lokesh Kanagaraj
Duration (mins)                            175
Hero                              Kamal Haasan
Movie Rating                               8.4
Revenue Collected (Crores)                 450
Name: 0, dtype: object

In [ ]:
moviedf.iloc[[0,-1]]

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf['Director'].nunique()

3

In [ ]:
moviedf['Director'].unique()

array(['Lokesh Kanagaraj', 'Mani Ratnam', 'Mari Selvaraj'], dtype=object)

In [ ]:
moviedf['Director'].value_counts()

Director
Lokesh Kanagaraj    3
Mani Ratnam         1
Mari Selvaraj       1
Name: count, dtype: int64

In [ ]:
moviedf.iloc[:3]

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300

In [ ]:
moviedf.index= ['m1','m2','m3','m4','m5']
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
m1,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
m2,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
m3,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
m4,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
m5,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf.loc['m1']

Movie Name                              Vikram
Director                      Lokesh Kanagaraj
Duration (mins)                            175
Hero                              Kamal Haasan
Movie Rating                               8.4
Revenue Collected (Crores)                 450
Name: m1, dtype: object

In [ ]:
moviedf.loc['m1':'m3']

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
m1,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
m2,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
m3,Master,Lokesh Kanagaraj,178,Vijay,7.3,300

#Slicing

similar to numpy 2d array

[row_Start: row_stop, colstart:col_stop]

In [ ]:
moviedf.iloc[0:2,0:2]

         Movie Name          Director
m1           Vikram  Lokesh Kanagaraj
m2  Ponniyin Selvan       Mani Ratnam

In [ ]:
moviedf.iloc[:,:2]

         Movie Name          Director
m1           Vikram  Lokesh Kanagaraj
m2  Ponniyin Selvan       Mani Ratnam
m3           Master  Lokesh Kanagaraj
m4           Karnan     Mari Selvaraj
m5           Kaithi  Lokesh Kanagaraj

In [ ]:
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
m1,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
m2,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
m3,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
m4,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
m5,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf.iloc[:,[0,3]]

         Movie Name          Hero
m1           Vikram  Kamal Haasan
m2  Ponniyin Selvan        Vikram
m3           Master         Vijay
m4           Karnan       Dhanush
m5           Kaithi        Karthi

In [ ]:
moviedf['Duration (mins)'] > 170

m1     True
m2    False
m3     True
m4    False
m5    False
Name: Duration (mins), dtype: bool

In [ ]:
moviedf[moviedf['Duration (mins)'] > 170]

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
m1,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
m3,Master,Lokesh Kanagaraj,178,Vijay,7.3,300

In [ ]:
LokeshMovies = moviedf[moviedf['Director'] == 'Lokesh Kanagaraj']
LokeshMovies

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
print(type(LokeshMovies))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
moviedf['year'] = [2019,2020,2021,2022,2023]
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores),year
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450,2019
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500,2020
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300,2021
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110,2022
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105,2023

In [ ]:
moviedf.drop('year') #axis=0 default that is row

KeyError: "['year'] not found in axis"

In [ ]:
moviedf.drop('year',axis=1) #axis=1 column

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores),year
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450,2019
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500,2020
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300,2021
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110,2022
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105,2023

In [ ]:
newdf = moviedf.drop('year',axis=1)
newdf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores),year
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450,2019
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500,2020
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300,2021
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110,2022
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105,2023

In [ ]:
moviedf.drop('year',axis=1,inplace=True)

In [ ]:
moviedf

,Movie Name,Director,Duration (mins),Hero,Movie Rating,Revenue Collected (Crores)
0,Vikram,Lokesh Kanagaraj,175,Kamal Haasan,8.4,450
1,Ponniyin Selvan,Mani Ratnam,167,Vikram,7.8,500
2,Master,Lokesh Kanagaraj,178,Vijay,7.3,300
3,Karnan,Mari Selvaraj,152,Dhanush,8.2,110
4,Kaithi,Lokesh Kanagaraj,145,Karthi,8.5,105

In [ ]:
newdf = moviedf.drop(columns =['Revenue Collected (Crores)','Duration (mins)'])
newdf

        Movie Name          Director          Hero  Movie Rating
0           Vikram  Lokesh Kanagaraj  Kamal Haasan           8.4
1  Ponniyin Selvan       Mani Ratnam        Vikram           7.8
2           Master  Lokesh Kanagaraj         Vijay           7.3
3           Karnan     Mari Selvaraj       Dhanush           8.2
4           Kaithi  Lokesh Kanagaraj        Karthi           8.5

# Session 14- Data Ingestion

fetching data from various sources

- csv - read_csv()
- using github raw link for csv files - read_csv()
- excel - read_excel()
- json - read_json()
- sql database - read_sql() - jupyter notebook
- html web page - read_html()

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#we will be storing the csv file into a dataframe

df= pd.read_csv('/content/titanic.csv')
df.head() #first 5 records

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#Data Exploration

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

#Statistical summary

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df['Embarked'].head(10)

0    S
1    C
2    S
3    S
4    S
5    Q
6    S
7    S
8    S
9    C
Name: Embarked, dtype: object

In [ ]:
df['Embarked'].nunique()

3

In [ ]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df['Age'].nunique()

88

In [ ]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [ ]:
df.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

#Uploading data using Github raw link

Recommended for your final project!

In [ ]:
df= pd.read_csv('https://raw.githubusercontent.com/narenmentor/Datasets/refs/heads/main/swiggy.csv')
df.head()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

#How to explore a dataframe ( csv file )

- df = pd.read_csv('link')
- df.head()
- df.info()
- df.describe()
- df.columns
- df.shape
- df.isnull().sum()

In [ ]:
df.isnull().sum()

ID               0
Area             0
City             0
Restaurant       0
Price            0
Avg ratings      0
Total ratings    0
Food type        0
Address          0
Delivery time    0
dtype: int64

In [ ]:
df.head(2)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56

## dont
 do like below!

In [ ]:
print(df.head(2))
print(df.describe())

    ID         Area       City     Restaurant  Price  Avg ratings  \
0  211  Koramangala  Bangalore    Tandoor Hut  300.0          4.4
1  221  Koramangala  Bangalore  Tunday Kababi  300.0          4.1

   Total ratings                                  Food type    Address  \
0            100  Biryani,Chinese,North Indian,South Indian  5Th Block
1            100                           Mughlai,Lucknowi  5Th Block

   Delivery time
0             59
1             56
                  ID        Price  Avg ratings  Total ratings  Delivery time
count    8680.000000  8680.000000  8680.000000    8680.000000    8680.000000
mean   244812.071429   348.444470     3.655104     156.634793      53.967051
std    158671.617188   230.940074     0.647629     391.448014      14.292335
min       211.000000     0.000000     2.000000      20.000000      20.000000
25%     72664.000000   200.000000     2.900000      50.000000      44.000000
50%    283442.000000   300.000000     3.900000      80.000000      53.000000
75%    393425.250000   400.000000     4.200000     100.000000      64.000000
max    466928.000000  2500.000000     5.000000   10000.000000     109.000000

#Data Wrangling

process of cleaning, transforming, organizing data!


- Merge - common key values
- Join - index
- concat - row wise or column wise appending
- GroupBy - performing aggregation operations

#1. merge() - Combining DataFrames on a Key


The merge() function in pandas is similar to SQL joins. It merges two DataFrames based on common column(s) or index.

merge(): Combines two DataFrames based on one or more common columns (keys).

It's similar to SQL joins. By default, it performs an inner join , but you can specify different types of joins using the how parameter.

The on parameter specifies the column(s) to join on, and if not provided, it defaults to the intersection of columns with the same name in both DataFrames.

Common join types:

Inner Join: It returns only the rows that have matching values in both DataFrames.

Outer Join: This join returns all rows from both DataFrames, with NaN in places where a DataFrame does not have a match.

Left Join: This join returns all rows from the left DataFrame and the matched rows from the right DataFrame. Rows in the left DataFrame with no match in the right DataFrame will have NaN for columns from the right DataFrame.

Right Join: This join returns all rows from the right DataFrame and the matched rows from the left DataFrame. Rows in the right DataFrame with no match in the left DataFrame will have NaN for columns from the left DataFrame.

#Syntax for Merge

- pd.merge(df1,df2,on,how)
- df1.merge(df2,on,how)
- pd.merge(df1,df2,left_on,right_on,how)

In [ ]:
# DataFrame 1: Team details
df_teams = pd.DataFrame({
    'Team': ['India', 'Australia', 'Pakistan', 'England', 'South Africa'],
    'Captain': ['MS Dhoni', 'Ricky Ponting', 'Sarfraz Ahmed', 'Eoin Morgan', 'AB de Villiers']
})
df_teams

           Team         Captain
0         India        MS Dhoni
1     Australia   Ricky Ponting
2      Pakistan   Sarfraz Ahmed
3       England     Eoin Morgan
4  South Africa  AB de Villiers

In [ ]:
# DataFrame 2: Match results
df_matches = pd.DataFrame({
    'Match_ID': [101, 102, 103, 104, 105],
    'Winner': ['India', 'Pakistan', 'Australia', 'England', 'New Zealand'],
    'Runner-up': ['South Africa', 'India', 'England', 'Pakistan', 'Australia']
})
df_matches

   Match_ID       Winner     Runner-up
0       101        India  South Africa
1       102     Pakistan         India
2       103    Australia       England
3       104      England      Pakistan
4       105  New Zealand     Australia

We want to get a list of matches where the winning team is in our team database, along with the captain of that team.

In [ ]:
df_inner = pd.merge(df_matches,df_teams,left_on="Winner",right_on="Team",how='inner')
df_inner

   Match_ID     Winner     Runner-up       Team        Captain
0       101      India  South Africa      India       MS Dhoni
1       102   Pakistan         India   Pakistan  Sarfraz Ahmed
2       103  Australia       England  Australia  Ricky Ponting
3       104    England      Pakistan    England    Eoin Morgan

In [ ]:
df_inner.drop('Team',axis=1,inplace=True)
#df_inner.drop(columns=['Team'],inplace=True)
df_inner

   Match_ID     Winner     Runner-up        Captain
0       101      India  South Africa       MS Dhoni
1       102   Pakistan         India  Sarfraz Ahmed
2       103  Australia       England  Ricky Ponting
3       104    England      Pakistan    Eoin Morgan

We want all matches and their winners, but if a winner is not in the team database, it should still be included with a missing captain.

In [ ]:
df_left = pd.merge(df_matches,df_teams,left_on="Winner",right_on="Team",how='left')
df_left

   Match_ID       Winner     Runner-up       Team        Captain
0       101        India  South Africa      India       MS Dhoni
1       102     Pakistan         India   Pakistan  Sarfraz Ahmed
2       103    Australia       England  Australia  Ricky Ponting
3       104      England      Pakistan    England    Eoin Morgan
4       105  New Zealand     Australia        NaN            NaN

# join() - Merging DataFrames Based on Index

join() is similar to merge(), but it joins DataFrames based on the index instead of a column.

The join() method in Pandas is primarily used for joining DataFrames based on their index.

It works like SQL joins but requires one DataFrame to have its index as the key. It is useful when merging on an index rather than a column.

In [ ]:
# DataFrame 1: Marvel Movies and Release Years
df_movies = pd.DataFrame({
    'Release_Year': [2008, 2012, 2014, 2018, 2019]
}, index=['Iron Man', 'The Avengers', 'Guardians of the Galaxy', 'Black Panther', 'Avengers: Endgame'])
df_movies

                         Release_Year
Iron Man                         2008
The Avengers                     2012
Guardians of the Galaxy          2014
Black Panther                    2018
Avengers: Endgame                2019

In [ ]:
df_box_office = pd.DataFrame({
    'Box_Office ($B)': [0.585, 1.519, 0.773, 1.347, 2.798]
}, index=['Iron Man', 'The Avengers', 'Guardians of the Galaxy', 'Black Panther', 'Avengers: Endgame'])
df_box_office

                         Box_Office ($B)
Iron Man                           0.585
The Avengers                       1.519
Guardians of the Galaxy            0.773
Black Panther                      1.347
Avengers: Endgame                  2.798

In [ ]:
df_box_office.index

Index(['Iron Man', 'The Avengers', 'Guardians of the Galaxy', 'Black Panther',
       'Avengers: Endgame'],
      dtype='object')

In [ ]:
df_joined = df_movies.join(df_box_office,how='inner')
df_joined

                         Release_Year  Box_Office ($B)
Iron Man                         2008            0.585
The Avengers                     2012            1.519
Guardians of the Galaxy          2014            0.773
Black Panther                    2018            1.347
Avengers: Endgame                2019            2.798

#Performing join

lets say we have common columns but there might be some scenario where we need to join that based on the index.

so we can set_index then join then again reset it!

In [ ]:
df_movies = pd.DataFrame({
    'Movie': ['Iron Man', 'The Avengers', 'Guardians of the Galaxy', 'Black Panther', 'Avengers: Endgame'],
    'Release_Year': [2008, 2012, 2014, 2018, 2019]
})
df_movies

                     Movie  Release_Year
0                 Iron Man          2008
1             The Avengers          2012
2  Guardians of the Galaxy          2014
3            Black Panther          2018
4        Avengers: Endgame          2019

In [ ]:
# DataFrame 2: Marvel Movies and Directors
df_directors = pd.DataFrame({
    'Movie': ['Iron Man', 'The Avengers', 'Guardians of the Galaxy', 'Black Panther'],
    'Director': ['Jon Favreau', 'Joss Whedon', 'James Gunn', 'Ryan Coogler']
})
df_directors

                     Movie      Director
0                 Iron Man   Jon Favreau
1             The Avengers   Joss Whedon
2  Guardians of the Galaxy    James Gunn
3            Black Panther  Ryan Coogler

In [ ]:
pd.merge(df_movies,df_directors,on='Movie',how='inner')

                     Movie  Release_Year      Director
0                 Iron Man          2008   Jon Favreau
1             The Avengers          2012   Joss Whedon
2  Guardians of the Galaxy          2014    James Gunn
3            Black Panther          2018  Ryan Coogler

In [ ]:
df_movies = df_movies.set_index('Movie')
df_directors = df_directors.set_index('Movie')
df_movies

                         Release_Year
Movie
Iron Man                         2008
The Avengers                     2012
Guardians of the Galaxy          2014
Black Panther                    2018
Avengers: Endgame                2019

In [ ]:
df_joined = df_movies.join(df_directors,how='inner')
df_joined

                         Release_Year      Director
Movie
Iron Man                         2008   Jon Favreau
The Avengers                     2012   Joss Whedon
Guardians of the Galaxy          2014    James Gunn
Black Panther                    2018  Ryan Coogler

In [ ]:
df_joined = df_joined.reset_index()
df_joined

                     Movie  Release_Year      Director
0                 Iron Man          2008   Jon Favreau
1             The Avengers          2012   Joss Whedon
2  Guardians of the Galaxy          2014    James Gunn
3            Black Panther          2018  Ryan Coogler

# concat() - Stacking DataFrames Together

concat(): Concatenates or appends DataFrames along a specified axis — vertically (row-wise axis=0) or horizontally (column-wise axis=1), with options to handle differing columns using outer or inner joins.

By default, it performs an outer join , including all columns or indices and filling in missing values with NaN.

To use an inner join , which only includes columns or indices present in all DataFrames, you can set the join parameter to 'inner'.

Unlike merge(), concat() is used to combine multiple DataFrames vertically (row-wise) or horizontally (column-wise).

Stacking datasets vertically (appending rows) – e.g., combining movie data from different years.

Merging datasets horizontally (side-by-side) – e.g., combining different attributes of the same movies.

pd.concat([df1,df2],ignore_index=False)

In [ ]:
# DataFrame 1: Marvel movies before 2015
df_marvel_1 = pd.DataFrame({
    'Movie': ['Iron Man', 'The Avengers', 'Guardians of the Galaxy'],
    'Release_Year': [2008, 2012, 2014],
    'Box_Office ($B)': [0.585, 1.519, 0.773]
})
df_marvel_1

                     Movie  Release_Year  Box_Office ($B)
0                 Iron Man          2008            0.585
1             The Avengers          2012            1.519
2  Guardians of the Galaxy          2014            0.773

In [ ]:
# DataFrame 2: Marvel movies after 2015
df_marvel_2 = pd.DataFrame({
    'Movie': ['Black Panther', 'Avengers: Endgame'],
    'Release_Year': [2018, 2019],
    'Box_Office ($B)': [1.347, 2.798]
})
df_marvel_2

               Movie  Release_Year  Box_Office ($B)
0      Black Panther          2018            1.347
1  Avengers: Endgame          2019            2.798

In [ ]:
moviedf=pd.concat([df_marvel_1,df_marvel_2]) #axis=0 row wise appending
moviedf

                     Movie  Release_Year  Box_Office ($B)
0                 Iron Man          2008            0.585
1             The Avengers          2012            1.519
2  Guardians of the Galaxy          2014            0.773
0            Black Panther          2018            1.347
1        Avengers: Endgame          2019            2.798

In [ ]:
moviedf=pd.concat([df_marvel_1,df_marvel_2],ignore_index=True) #axis=0 row wise appending
moviedf

                     Movie  Release_Year  Box_Office ($B)
0                 Iron Man          2008            0.585
1             The Avengers          2012            1.519
2  Guardians of the Galaxy          2014            0.773
3            Black Panther          2018            1.347
4        Avengers: Endgame          2019            2.798

In [ ]:
df_movie_info = pd.DataFrame({
    'Movie': ['Iron Man', 'The Avengers', 'Guardians of the Galaxy', 'Black Panther', 'Avengers: Endgame'],
    'Release_Year': [2008, 2012, 2014, 2018, 2019]
})

df_directors = pd.DataFrame({
    'Movie': ['Iron Man', 'Guardians of the Galaxy', 'The Avengers', 'Black Panther', 'Avengers: Endgame'],
    'Director': ['Jon Favreau', 'James Gunn', 'Joss Whedon', 'Ryan Coogler', 'Anthony & Joe Russo']
})
df_directors

                     Movie             Director
0                 Iron Man          Jon Favreau
1  Guardians of the Galaxy           James Gunn
2             The Avengers          Joss Whedon
3            Black Panther         Ryan Coogler
4        Avengers: Endgame  Anthony & Joe Russo

In [ ]:
df_movie_info

                     Movie  Release_Year
0                 Iron Man          2008
1             The Avengers          2012
2  Guardians of the Galaxy          2014
3            Black Panther          2018
4        Avengers: Endgame          2019

In [ ]:
pd.merge(df_movie_info,df_directors,on='Movie',how='inner')

                     Movie  Release_Year             Director
0                 Iron Man          2008          Jon Favreau
1             The Avengers          2012          Joss Whedon
2  Guardians of the Galaxy          2014           James Gunn
3            Black Panther          2018         Ryan Coogler
4        Avengers: Endgame          2019  Anthony & Joe Russo

In [ ]:
moviedf=pd.concat([df_movie_info,df_directors['Director']],axis=1) #axis=0 row wise appending
moviedf

                     Movie  Release_Year             Director
0                 Iron Man          2008          Jon Favreau
1             The Avengers          2012           James Gunn
2  Guardians of the Galaxy          2014          Joss Whedon
3            Black Panther          2018         Ryan Coogler
4        Avengers: Endgame          2019  Anthony & Joe Russo

# groupby() - Grouping and Aggregating Data

The groupby() function in Pandas is used to group data based on one or more columns and apply aggregate functions like sum, mean, count, etc. It is particularly useful for summarizing and analyzing large datasets.

In [ ]:
data = {
    'Player': ['LeBron James', 'Stephen Curry', 'Kevin Durant', 'LeBron James', 'Stephen Curry', 'Kevin Durant', 'Giannis Antetokounmpo'],
    'Team': ['Lakers', 'Warriors', 'Suns', 'Lakers', 'Warriors', 'Suns', 'Bucks'],
    'Season': ['2022', '2022', '2022', '2023', '2023', '2023', '2023'],
    'Points': [1500, 1700, 1600, 1800, 1750, 1650, 2000]
}
df_nba=pd.DataFrame(data)
df_nba

                  Player      Team Season  Points
0           LeBron James    Lakers   2022    1500
1          Stephen Curry  Warriors   2022    1700
2           Kevin Durant      Suns   2022    1600
3           LeBron James    Lakers   2023    1800
4          Stephen Curry  Warriors   2023    1750
5           Kevin Durant      Suns   2023    1650
6  Giannis Antetokounmpo     Bucks   2023    2000

In [ ]:
team_total_points = df_nba.groupby('Team')['Points'].sum()
team_total_points

Team
Bucks       2000
Lakers      3300
Suns        3250
Warriors    3450
Name: Points, dtype: int64

In [ ]:
team_total_points = df_nba.groupby('Team')['Points'].sum().reset_index()
team_total_points

       Team  Points
0     Bucks    2000
1    Lakers    3300
2      Suns    3250
3  Warriors    3450

In [ ]:
team_stats = df_nba.groupby('Team').agg(
    total_points = ('Points','sum'),
    avg_points = ('Points','mean'),
    playercount = ('Player','count')
).reset_index()
team_stats

       Team  total_points  avg_points  playercount
0     Bucks          2000      2000.0            1
1    Lakers          3300      1650.0            2
2      Suns          3250      1625.0            2
3  Warriors          3450      1725.0            2